import type { EdgeType, EvidenceLevel, GraphEdge, Layer } from "./types";

function e(
  source: string,
  target: string,
  type: EdgeType,
  label: string,
  evidenceLevel: EvidenceLevel,
  layers: Layer[],
  description: string,
  loopId?: string,
): GraphEdge {
  const slug = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
  return {
    id: `${source}>${target}:${type}:${slug}`,
    source,
    target,
    type,
    label,
    description,
    evidenceLevel,
    layers,
    loopId,
  };
}

/** Directed relationships in the educational model. Labels are mechanisms, not verdicts. */
export const EDGES: GraphEdge[] = [
  // Core star around human behavior
  e("human-behavior", "attention", "causal", "Allocates scarce focus", "established", ["psychology"], "People spend limited attention on competing stimuli."),
  e("human-behavior", "data", "data", "Leaves traces", "established", ["data"], "Actions are recorded by products, states, and sensors."),
  e("human-behavior", "labor", "dependency", "Supplies work", "established", ["labor"], "Production still requires human time and skill in most sectors."),
  e("human-behavior", "consumption", "causal", "Chooses and spends", "established", ["money", "psychology"], "Households turn income and credit into purchases."),
  e("attention", "human-behavior", "influence", "Steers what is done next", "observed", ["psychology"], "What is noticed is more likely to be chosen."),
  e("data", "ai-systems", "data", "Trains and evaluates models", "established", ["ai", "data"], "Modern AI systems are fit to recorded data."),
  e("technology", "business-firms", "dependency", "Changes what is cheap to offer", "established", ["business"], "Tools shift cost curves and product possibility."),
  e("business-firms", "human-behavior", "incentive", "Prices, defaults, jobs", "observed", ["business"], "Firms structure options people face."),
  e("capital", "business-firms", "money", "Funds operations and assets", "established", ["money"], "Equity and credit purchase capacity."),
  e("government", "business-firms", "regulation", "Sets legal constraints", "established", ["power"], "Licenses, tax, labor, and product rules."),
  e("media", "human-behavior", "information", "Frames events", "observed", ["information"], "Packaged stories reach people through attention."),
  e("ai-systems", "human-behavior", "influence", "Recommendations and tools", "observed", ["ai", "psychology"], "Model outputs enter choices and workflows."),
  e("labor", "business-firms", "dependency", "Produces output", "established", ["labor"], "Firms combine labor with capital."),
  e("consumption", "business-firms", "money", "Purchases / revenue", "established", ["money"], "Customer spending is the cash validation of production."),

  // Money layer
  e("capital", "investors", "ownership", "Claims on residual cash flows", "established", ["money"], "Ownership is a legal claim, not a physical pile of cash."),
  e("investors", "capital", "money", "Allocated funds", "established", ["money"], "Savings and mandates become investable capital."),
  e("investors", "business-firms", "money", "Capital", "established", ["money"], "Equity and some credit from investors to firms."),
  e("business-firms", "employees", "money", "Wages", "established", ["money", "labor"], "Payroll is a primary distribution of firm cash."),
  e("employees", "consumers", "causal", "Households overlap workers", "established", ["labor", "money"], "The same people often work and buy."),
  e("consumers", "business-firms", "money", "Purchases", "established", ["money"], "Retail and B2C cash flow."),
  e("business-firms", "revenue", "money", "Sales recorded", "established", ["money", "business"], "Accounting identity: sales become revenue."),
  e("revenue", "profit", "money", "After costs", "established", ["money"], "Profit is residual, definition-dependent."),
  e("profit", "investors", "money", "Expected financial return", "observed", ["money"], "Distributions and valuation depend on expected residual cash."),
  e("profit", "shareholder-returns", "money", "Dividends and buybacks", "observed", ["money"], "One use of surplus, not mandatory."),
  e("shareholder-returns", "investors", "money", "Cash returned", "established", ["money"], "Closes the owner loop."),
  e("profit", "reinvestment", "money", "Retained earnings", "established", ["money", "business"], "Internal capital allocation.", "capital-loop"),
  e("reinvestment", "growth", "money", "Capacity and product spend", "observed", ["business"], "Reinvestment aims at a larger future firm.", "capital-loop"),
  e("growth", "revenue", "money", "Larger top line", "plausible", ["business", "money"], "Scale can raise sales if demand exists.", "capital-loop"),
  e("revenue", "profit", "feedback", "More residual if costs lag", "plausible", ["money"], "Reinforcing when unit economics hold.", "capital-loop"),
  e("banks", "credit", "money", "Loan origination", "established", ["money"], "Banks extend purchasing power under constraints."),
  e("credit", "business-firms", "money", "Borrowed funds", "established", ["money"], "Credit finances working capital and investment."),
  e("credit", "consumption", "money", "Household borrowing", "established", ["money"], "Mortgages, cards, and installment credit."),
  e("credit", "debt", "money", "Liability created", "established", ["money"], "Flow of credit becomes a stock of debt."),
  e("debt", "banks", "money", "Servicing", "established", ["money"], "Interest and principal return to lenders."),
  e("business-firms", "banks", "money", "Interest and fees", "established", ["money"], "Firms pay for credit and payments."),
  e("interest-rates", "credit", "influence", "Price of borrowing", "established", ["money"], "Higher rates ration credit, all else equal."),
  e("interest-rates", "capital", "influence", "Discount rates", "established", ["money"], "Asset prices embed expected rates."),
  e("markets", "capital", "information", "Price discovery", "established", ["money"], "Quoted prices inform allocation."),
  e("business-firms", "markets", "information", "Earnings and guidance", "observed", ["money"], "Disclosures move prices."),
  e("revenue", "taxes", "money", "Corporate and sales tax base", "established", ["money", "power"], "Taxable events follow commerce."),
  e("consumers", "taxes", "money", "Income and consumption tax", "established", ["money", "power"], "Households fund the fiscal state."),
  e("taxes", "government", "money", "Fiscal revenue", "established", ["money", "power"], "States spend what they can tax, borrow, or create."),
  e("wages", "consumption", "money", "Purchasing power", "established", ["labor", "money"], "Pay funds household demand."),
  e("profit", "wages", "incentive", "Bargain over surplus", "observed", ["labor", "money"], "How residual splits is institutional, not automatic."),

  // Information layer
  e("users", "social-platforms", "data", "Attention / behavioral data", "established", ["information", "data"], "Use produces logs and inventory.", "attention-loop"),
  e("social-platforms", "users", "information", "Recommendation / content ranking", "established", ["information"], "Platforms return a ranked experience.", "attention-loop"),
  e("social-platforms", "recommendation-algorithms", "data", "Interaction logs", "established", ["information", "ai"], "Rankers train and score on traces."),
  e("recommendation-algorithms", "content", "information", "Ranked inventory", "established", ["information", "ai"], "The algorithm orders what can be seen.", "attention-loop"),
  e("content", "attention", "information", "Competes for focus", "established", ["information", "psychology"], "Messages must pass the attention bottleneck.", "attention-loop"),
  e("attention", "engagement", "causal", "Time and interaction", "observed", ["psychology"], "Noticing is a precondition for clicking and lingering.", "attention-loop"),
  e("engagement", "data-collection", "data", "Behavioral traces", "established", ["data"], "Interactions are logged.", "attention-loop"),
  e("data-collection", "personalization", "data", "Preference model inputs", "observed", ["data", "ai"], "Logs become features.", "attention-loop"),
  e("personalization", "recommendation-algorithms", "data", "User-specific scores", "observed", ["ai"], "Personalization is often implemented as ranking.", "attention-loop"),
  e("personalization", "engagement", "feedback", "More relevant stimuli", "observed", ["psychology", "ai"], "Better targeting can raise measured engagement.", "attention-loop"),
  e("journalists", "news-ecosystem", "information", "Reported stories", "established", ["information"], "Original reporting enters the wider news system."),
  e("news-ecosystem", "media", "information", "Packaged news", "observed", ["information"], "Outlets select and frame."),
  e("media", "public-opinion", "information", "Agenda and framing", "observed", ["information", "power"], "Coverage shapes what is thinkable as 'the issue'."),
  e("public-opinion", "government", "influence", "Electoral and legitimacy pressure", "observed", ["power"], "Office-holders respond, imperfectly, to publics."),
  e("public-opinion", "political-influence", "influence", "Voter and donor signals", "observed", ["power"], "Opinion is an input to organized politics."),
  e("researchers", "publications", "information", "Papers and preprints", "established", ["information"], "The formal knowledge channel."),
  e("publications", "ai-laboratories", "information", "Methods and results", "observed", ["ai"], "Labs absorb and extend published methods."),
  e("publications", "products", "information", "Applied research", "plausible", ["business", "ai"], "Some papers become product features, with lag."),
  e("researchers", "universities", "dependency", "Appointments and grants", "established", ["labor"], "Much research labor is hosted in universities."),
  e("universities", "researchers", "dependency", "Employment and students", "established", ["labor"], "Two-way: institutions need faculty; faculty need posts."),
  e("content", "media", "information", "Stories and clips", "observed", ["information"], "User and professional content feed outlets."),
  e("media", "attention", "information", "Headlines and packages", "observed", ["information", "psychology"], "News competes in the same attention market."),
  e("search-platforms", "distribution", "information", "Query-based discovery", "observed", ["information", "business"], "Search is a major path to products and publishers."),
  e("social-platforms", "distribution", "information", "Feed-based discovery", "observed", ["information", "business"], "Feeds allocate attention among offers."),
  e("media", "information-power", "influence", "Agenda control", "plausible", ["power", "information"], "Who is heard is a form of power."),
  e("social-platforms", "information-power", "influence", "Ranking is allocation", "plausible", ["power", "information"], "Ordering content is a political-economic act even when not intended as such."),

  // Data layer
  e("human-behavior", "data-collection", "data", "Observed actions", "established", ["data"], "Instrumentation captures behavior."),
  e("data-collection", "data-storage", "data", "Logged records", "established", ["data"], "Collection implies retention unless deleted."),
  e("data-storage", "datasets", "data", "Assembled corpora", "established", ["data", "ai"], "Stored logs are sliced into training and analytics sets."),
  e("data-collection", "data-brokers", "data", "Sold or shared records", "observed", ["data"], "Some traces leave the first party."),
  e("data-brokers", "datasets", "data", "Appended attributes", "observed", ["data"], "Brokers enrich profiles."),
  e("datasets", "machine-learning", "data", "Training inputs", "established", ["ai", "data"], "Learning consumes packaged data."),
  e("machine-learning", "predictions", "data", "Scores and forecasts", "established", ["ai"], "Fitted functions emit decisions support."),
  e("predictions", "business-firms", "causal", "Operational decisions", "observed", ["business", "data"], "Scores change who is hired, priced, shown, or funded."),
  e("predictions", "advertising", "data", "Targeting", "observed", ["business", "data"], "Predicted conversion allocates ad spend."),
  e("predictions", "human-behavior", "influence", "Interventions and defaults", "plausible", ["psychology", "data"], "Acting on a score changes the environment of choice."),
  e("data", "datasets", "data", "Structured for training", "established", ["data", "ai"], "Raw traces are cleaned and labeled."),
  e("privacy", "data-collection", "regulation", "Consent and limits", "observed", ["data", "power"], "Rules and norms constrain capture."),
  e("users", "data", "data", "Generated traces", "established", ["data"], "Use is the source of much behavioral data."),
  e("data", "data-brokers", "money", "Data as asset", "observed", ["data", "money"], "Records are bought and sold."),
  e("data-brokers", "advertisers", "data", "Audience segments", "observed", ["data", "business"], "Targeting inventory is a broker product."),
  e("privacy", "trust", "causal", "Expectation of boundaries", "plausible", ["psychology", "data"], "Perceived respect for boundaries supports trust."),

  // AI stack
  e("content", "data", "data", "Human-generated information", "established", ["ai", "information"], "Text and media become training material."),
  e("datasets", "training-infrastructure", "data", "Job inputs", "established", ["ai"], "Clusters consume packaged data."),
  e("gpus", "training-infrastructure", "supply", "Accelerators", "established", ["ai", "supply"], "Training is bottlenecked on specialized chips."),
  e("training-infrastructure", "neural-networks", "dependency", "Compute for training", "established", ["ai"], "Weights are the output of long jobs."),
  e("neural-networks", "llms", "dependency", "Trained weights", "established", ["ai"], "LLMs are a scaled neural product."),
  e("neural-networks", "ai-systems", "dependency", "Model family", "established", ["ai"], "Most deployed 'AI' is neural."),
  e("llms", "inference", "dependency", "Serving", "established", ["ai"], "Products call trained models."),
  e("inference", "applications", "dependency", "API / product calls", "established", ["ai"], "Apps are the wrapper.", "ai-loop"),
  e("applications", "users", "information", "Model outputs", "observed", ["ai"], "People meet models in products.", "ai-loop"),
  e("users", "data", "data", "New interaction signals", "observed", ["ai", "data"], "Use creates the next corpus.", "ai-loop"),
  e("data", "datasets", "feedback", "Updated corpora", "observed", ["ai", "data"], "The flywheel of product data.", "ai-loop"),
  e("ai-laboratories", "neural-networks", "causal", "Research and training runs", "observed", ["ai"], "Labs choose architectures and spends."),
  e("ai-laboratories", "llms", "causal", "Frontier training", "observed", ["ai"], "A few orgs train the largest models."),
  e("developers", "applications", "causal", "Productization", "established", ["ai", "labor"], "Engineers wrap models."),
  e("agents", "automation", "causal", "Task execution", "plausible", ["ai", "labor"], "Agents aim to take multi-step actions."),
  e("inference", "agents", "dependency", "Runtime", "plausible", ["ai"], "Agents are loops around inference."),
  e("cloud-infrastructure", "training-infrastructure", "supply", "Cluster hosting", "established", ["ai", "supply"], "Most training runs on rented or owned cloud."),
  e("data-centers", "cloud-infrastructure", "supply", "Buildings, power, cooling", "established", ["supply"], "Cloud is a business model on top of buildings."),
  e("semiconductors", "gpus", "supply", "Fabricated chips", "established", ["supply", "ai"], "Accelerators are silicon."),
  e("chip-foundries", "semiconductors", "supply", "Wafer production", "established", ["supply"], "Fabs turn designs into chips."),
  e("chip-foundries", "gpus", "supply", "Advanced nodes", "established", ["supply", "ai"], "Leading GPUs need leading processes."),
  e("energy", "data-centers", "supply", "Electricity", "established", ["supply"], "Compute is an energy story."),
  e("hardware", "data-centers", "supply", "Servers", "established", ["supply"], "Racks of machines."),
  e("ai-systems", "applications", "dependency", "Embedded models", "observed", ["ai"], "Products hide models behind UX."),
  e("llms", "content", "information", "Generated media", "observed", ["ai", "information"], "Models now produce some of the corpus."),
  e("machine-learning", "recommendation-algorithms", "dependency", "Scoring functions", "established", ["ai"], "Rankers are ML systems."),
  e("ai-systems", "automation", "causal", "Cognitive automation", "observed", ["ai", "labor"], "Prediction and generation substitute for some tasks."),

  // Psychology extras
  e("attention", "curiosity", "causal", "Information gap", "plausible", ["psychology"], "Gaps in knowledge pull exploration."),
  e("curiosity", "engagement", "causal", "Exploration clicks", "plausible", ["psychology"], "Curiosity is monetizable."),
  e("engagement", "reward", "causal", "Variable reinforcement", "observed", ["psychology"], "Likes, novelty, and completion pings."),
  e("reward", "habit", "causal", "Repeated cue-routine", "observed", ["psychology"], "Payoffs stamp in routines."),
  e("habit", "human-behavior", "causal", "Automatic repetition", "observed", ["psychology"], "Habits reduce deliberation."),
  e("attention", "social-platforms", "incentive", "Inventory for ads", "established", ["business", "psychology"], "Attention is what many platforms sell."),
  e("social-status", "identity", "causal", "Self-presentation", "plausible", ["psychology"], "Status work is identity work."),
  e("social-proof", "engagement", "influence", "What others do", "observed", ["psychology"], "Counts and faces raise interaction."),
  e("novelty", "attention", "causal", "Salience", "observed", ["psychology"], "Newness is a cheap way to be noticed."),
  e("fear", "attention", "causal", "Threat monitoring", "observed", ["psychology"], "Threat cues are sticky."),
  e("loss-aversion", "consumption", "incentive", "Avoiding perceived loss", "plausible", ["psychology", "business"], "Framing losses can move purchases."),
  e("trust", "business-firms", "dependency", "Willingness to transact", "established", ["business", "psychology"], "Exchange needs expected performance."),
  e("trust", "media", "dependency", "Believed sources", "observed", ["information"], "Outlets live on residual credibility."),
  e("identity", "tribal-behavior", "causal", "In-group signaling", "plausible", ["psychology"], "Identity can polarize information diets."),
  e("scarcity", "attention", "causal", "Urgency", "observed", ["psychology"], "Limited-time cues spike focus."),
  e("convenience", "habit", "causal", "Lower friction", "observed", ["psychology"], "Ease is a habit ingredient."),
  e("authority", "trust", "influence", "Credentialed cues", "observed", ["psychology", "power"], "Titles and institutions shortcut evaluation."),
  e("social-status", "consumption", "incentive", "Positional goods", "observed", ["psychology", "money"], "Some demand is rank-seeking."),
  e("habit", "retention", "causal", "Psychological lock-in", "observed", ["business", "psychology"], "Habits raise the cost of leaving."),

  // Business layer
  e("products", "distribution", "dependency", "Go-to-market", "established", ["business"], "Offers need a path to customers."),
  e("distribution", "customer-acquisition", "causal", "Reach", "established", ["business"], "Channels produce candidates."),
  e("customer-acquisition", "conversion", "causal", "Funnel", "established", ["business"], "Not all reach pays."),
  e("conversion", "revenue", "money", "Paid conversion", "established", ["business", "money"], "The cash event."),
  e("customer-acquisition", "cac", "money", "Acquisition cost", "established", ["business"], "Fully loaded cost per customer."),
  e("retention", "ltv", "money", "Lifetime value", "observed", ["business"], "Duration and margin make LTV."),
  e("cac", "ltv", "correlation", "Unit-economics ratio", "observed", ["business"], "Sustainable paid growth needs LTV above CAC — a rule of thumb, not a law."),
  e("advertising", "customer-acquisition", "information", "Paid reach", "established", ["business"], "Ads buy attention in channels."),
  e("advertisers", "advertising", "money", "Ad spend", "established", ["business", "money"], "Budgets are the fuel."),
  e("advertising", "social-platforms", "money", "Platform revenue", "established", ["business", "money"], "A primary cash engine of consumer platforms."),
  e("social-platforms", "advertisers", "information", "Audience access", "established", ["business"], "The other side of the market."),
  e("advertising", "search-platforms", "money", "Intent inventory", "established", ["business", "money"], "Query ads sell high-intent attention."),
  e("business-firms", "products", "causal", "Offers", "established", ["business"], "Firms package solutions."),
  e("products", "consumers", "information", "Value proposition", "observed", ["business"], "Messaging and use."),
  e("innovation", "products", "causal", "New offers", "observed", ["business"], "Successful novelty becomes SKUs.", "competition-loop"),
  e("competition", "innovation", "incentive", "Response to rivals", "observed", ["business"], "Rivalry can force product change.", "competition-loop"),
  e("innovation", "competition", "feedback", "Raised bar", "plausible", ["business"], "New tech resets expectations.", "competition-loop"),
  e("competition", "products", "causal", "Differentiation pressure", "observed", ["business"], "Samelessness is punished when alternatives exist."),
  e("competition", "advertising", "incentive", "Share of voice", "observed", ["business"], "Rivals bid up attention."),
  e("network-effects", "moats", "causal", "Winner-take-most dynamics", "plausible", ["business"], "When they hold, they entrench."),
  e("switching-costs", "moats", "causal", "Lock-in", "observed", ["business"], "Friction is a defensive asset."),
  e("moats", "pricing-power", "causal", "Ability to hold price", "plausible", ["business"], "Advantage can become margin."),
  e("pricing-power", "margins", "money", "Unit economics", "observed", ["business", "money"], "Price over cost."),
  e("economies-of-scale", "margins", "money", "Falling average cost", "established", ["business"], "Volume can dilute fixed cost."),
  e("network-effects", "social-platforms", "causal", "Value with more users", "observed", ["business"], "Communication products often scale this way."),
  e("growth", "market-power", "causal", "Share can weaken rivalry", "plausible", ["business", "power"], "Size is not automatically power, but it can be."),
  e("market-power", "pricing-power", "causal", "Set terms", "observed", ["business"], "Weak alternatives raise prices."),
  e("reinvestment", "products", "money", "Roadmap funding", "observed", ["business"], "R&D and production."),
  e("revenue", "employees", "money", "Payroll funding", "established", ["business", "labor"], "People are paid from operations or capital."),

  // Power / institutions
  e("government", "regulators", "regulation", "Statutory mandate", "established", ["power"], "Agencies exist by law."),
  e("regulators", "business-firms", "regulation", "Rules and licenses", "established", ["power"], "Permitted activity is a legal fact."),
  e("business-firms", "lobbying", "money", "Advocacy spend", "observed", ["power"], "Legal organized persuasion is budgeted."),
  e("lobbying", "government", "influence", "Legal persuasion", "observed", ["power"], "Access and argument, not automatically capture."),
  e("lobbying", "regulators", "influence", "Comment and access", "observed", ["power"], "Rule-making is a documented channel."),
  e("public-opinion", "public-pressure", "causal", "Mobilization", "observed", ["power"], "Attitudes become costly when organized."),
  e("public-pressure", "government", "influence", "Political cost of inaction", "observed", ["power"], "Protests, virality, and voting blocs."),
  e("public-pressure", "regulators", "influence", "Enforcement priorities", "plausible", ["power"], "Salient scandals move dockets."),
  e("media", "public-pressure", "information", "Amplifies campaigns", "observed", ["information", "power"], "Coverage is oxygen."),
  e("government", "courts", "regulation", "Appointment and statute", "established", ["power"], "Judiciaries are constituted by law."),
  e("courts", "business-firms", "regulation", "Adjudication", "established", ["power"], "Contracts and liability."),
  e("courts", "regulators", "regulation", "Judicial review", "established", ["power"], "Agencies can be checked."),
  e("government", "taxes", "regulation", "Tax code", "established", ["power", "money"], "The schedule of compulsory transfer."),
  e("banks", "government", "influence", "Systemic importance", "observed", ["power", "money"], "Crisis backstops create a political channel."),
  e("government", "banks", "regulation", "Prudential rules", "established", ["power", "money"], "Capital, liquidity, conduct."),
  e("business-firms", "political-influence", "money", "Donations and PACs", "observed", ["power"], "Legal political spending in some jurisdictions — not a claim of hidden control."),
  e("political-influence", "government", "influence", "Campaign and coalition", "observed", ["power"], "Organized interests seek office-holder attention."),
  e("capital", "political-influence", "influence", "Resource advantage", "plausible", ["power", "money"], "Money is one input to politics, not the only one."),
  e("government", "labor", "regulation", "Labor law", "established", ["power", "labor"], "Hours, unions, migration, safety."),
  e("regulators", "privacy", "regulation", "Data protection rules", "observed", ["power", "data"], "A growing domain of administrative law."),
  e("courts", "privacy", "regulation", "Case law on data and speech", "observed", ["power", "data"], "Disputes refine the boundary."),

  // Supply chain
  e("natural-resources", "raw-materials", "supply", "Extraction", "established", ["supply"], "Ores, fuels, water, biomass."),
  e("raw-materials", "manufacturing", "supply", "Industrial inputs", "established", ["supply"], "Chemicals, metals, substrates."),
  e("manufacturing", "semiconductors", "supply", "Tools and materials", "established", ["supply"], "Fabs sit inside a wider industrial web."),
  e("semiconductors", "hardware", "supply", "Chips in devices", "established", ["supply"], "Every computer is a materials story."),
  e("hardware", "software", "dependency", "Where code runs", "established", ["supply"], "Software assumes a machine."),
  e("software", "distribution", "dependency", "Delivery of capability", "observed", ["supply", "business"], "Bits still need a channel."),
  e("distribution", "business-firms", "dependency", "Channel access", "observed", ["business"], "Firms without distribution stall."),
  e("business-firms", "consumers", "supply", "Goods and services", "established", ["supply", "business"], "The last hop."),
  e("energy", "manufacturing", "supply", "Industrial power", "established", ["supply"], "Heat and work."),
  e("energy", "hardware", "supply", "Use-phase electricity", "established", ["supply"], "Devices draw power."),
  e("supply-chains", "manufacturing", "dependency", "Logistics", "established", ["supply"], "Parts must arrive."),
  e("semiconductors", "technology", "supply", "Physical basis of compute", "established", ["supply"], "Digital technology is embodied."),
  e("manufacturing", "hardware", "supply", "Assembly", "established", ["supply"], "Boards and boxes."),
  e("cloud-infrastructure", "software", "dependency", "Hosted runtime", "observed", ["supply", "business"], "Much software now assumes the cloud."),

  // Labor / automation
  e("labor", "employees", "dependency", "Contractual form", "established", ["labor"], "Employment is one institution of labor."),
  e("workers", "labor", "dependency", "Labor supply", "established", ["labor"], "People available to work."),
  e("employees", "productivity", "causal", "Output of work", "established", ["labor"], "Hours and skill become goods."),
  e("automation", "productivity", "causal", "Output per hour", "observed", ["labor", "ai"], "Machines can raise measured productivity."),
  e("productivity", "profit", "money", "Lower unit cost / more output", "plausible", ["labor", "money"], "Gains may accrue to owners if prices and wages do not absorb them."),
  e("automation", "job-transformation", "causal", "Task mix change", "observed", ["labor", "ai"], "Tasks are rewritten; occupations lag."),
  e("job-transformation", "skills", "causal", "New skill demand", "observed", ["labor"], "Complements to new tools become valuable."),
  e("skills", "wages", "causal", "Skill premium", "contested", ["labor"], "Premiums exist; how much is skill versus bargaining is debated."),
  e("skills", "employees", "dependency", "Capability", "established", ["labor"], "Hiring screens for skills."),
  e("automation", "wages", "influence", "Pressure on routine pay", "contested", ["labor"], "Direction and magnitude vary by task and country."),
  e("job-transformation", "workers", "causal", "Occupational change", "observed", ["labor"], "People must switch tasks or roles."),
  e("universities", "skills", "information", "Credentials and training", "observed", ["labor"], "One of several skill factories."),
  e("growth", "labor", "incentive", "Hiring", "observed", ["labor", "business"], "Expanding firms demand hours."),
  e("productivity", "wages", "causal", "Room to pay more", "contested", ["labor"], "Long-run link is real in aggregates; short-run pass-through is not guaranteed."),
  e("ai-systems", "job-transformation", "causal", "Cognitive task rewrite", "plausible", ["ai", "labor"], "Language and vision models change office task mix."),
  e("wages", "inequality", "causal", "Pay dispersion", "observed", ["labor"], "Wage structure is one component of inequality."),
  e("capital", "inequality", "causal", "Ownership of claims", "observed", ["money"], "Return on capital is unevenly held."),
  e("inequality", "political-influence", "influence", "Uneven voice", "plausible", ["power"], "Resources can buy organization — a mechanism, not a hidden plot."),

  // Extra useful links
  e("advertisers", "revenue", "money", "A demand source for media", "established", ["money", "business"], "Ad budgets are revenue for platforms and publishers."),
  e("recommendation-algorithms", "advertising", "incentive", "Maximize yield", "observed", ["business", "ai"], "Some rankers directly optimize ad value."),
  e("cloud-infrastructure", "economies-of-scale", "causal", "Fixed cost dilution", "observed", ["business", "supply"], "Hyperscale spreads capex."),
  e("gpus", "inference", "supply", "Serving hardware", "established", ["ai", "supply"], "Inference also consumes accelerators."),
  e("energy", "ai-systems", "dependency", "Training and serving power", "established", ["ai", "supply"], "The stack is thermodynamic."),
  e("trust", "consumption", "dependency", "Willingness to pay", "observed", ["business", "psychology"], "Scams and failures tax demand."),
  e("regulators", "competition", "regulation", "Antitrust and merger review", "established", ["power", "business"], "A legal attempt to preserve rivalry."),
  e("public-opinion", "business-firms", "influence", "Brand and license to operate", "observed", ["power", "business"], "Boycotts and hiring markets."),
  e("developers", "software", "causal", "Implementation", "established", ["labor"], "Code is written and maintained by people — still."),
  e("software", "applications", "dependency", "Product is software", "established", ["ai", "business"], "Wrappers are programs."),
  e("applications", "revenue", "money", "Subscriptions and usage", "observed", ["business"], "Many AI apps charge seats or tokens."),
  e("inference", "revenue", "money", "Metered cost passed through", "plausible", ["ai", "money"], "Cheaper inference can expand or cheapen products."),
];
