import type {
  Category,
  Claim,
  EvidenceLevel,
  GraphNode,
  Layer,
  Tension,
} from "./types";

type Draft = {
  id: string;
  name: string;
  category: Category;
  layers: Layer[];
  tier: 0 | 1 | 2;
  description: string;
  role: string;
  importance?: number;
  evidenceLevel?: EvidenceLevel;
  incentives?: string[];
  inputs?: string[];
  outputs?: string[];
  dependencies?: string[];
  whoBenefits?: string[];
  whoBearsCosts?: string[];
  relatedSystems?: string[];
  uncertainties?: string[];
  positiveEffects?: string[];
  negativeExternalities?: string[];
  unintendedConsequences?: string[];
  optimizesFor?: string;
  resources?: string[];
  gains?: string[];
  risks?: string[];
  whoPays?: string[];
  encouragedBehavior?: string;
  unintendedBehavior?: string;
  aliases?: string[];
  claims?: Claim[];
  tensions?: Tension[];
  geographicNote?: string;
};

function N(d: Draft): GraphNode {
  return {
    importance: d.tier === 0 ? 9 : d.tier === 1 ? 6 : 4,
    evidenceLevel: "observed",
    incentives: [],
    inputs: [],
    outputs: [],
    dependencies: [],
    whoBenefits: [],
    whoBearsCosts: [],
    relatedSystems: [],
    uncertainties: [],
    positiveEffects: [],
    negativeExternalities: [],
    unintendedConsequences: [],
    optimizesFor: d.role,
    resources: [],
    gains: [],
    risks: [],
    whoPays: [],
    encouragedBehavior: "",
    unintendedBehavior: "",
    ...d,
  };
}

/** Simplified educational model of archetypal systems — not a census of firms. */
export const NODES: GraphNode[] = [
  N({
    id: "human-behavior",
    name: "Human behavior",
    category: "human",
    layers: ["psychology", "data", "labor"],
    tier: 0,
    importance: 10,
    evidenceLevel: "established",
    aliases: ["people", "humans", "behavior"],
    description:
      "The observable actions, choices, and habits of people. In this model it is the hub: behavior generates data, spends money, supplies labor, and responds to incentives, rankings, and institutions.",
    role: "Source of demand, labor, attention, and the traces that other systems learn from.",
    incentives: [
      "Seek reward, status, belonging, and reduced effort",
      "Avoid loss, uncertainty, and social exclusion",
    ],
    inputs: ["Incentives", "Information", "Prices", "Defaults", "Social cues"],
    outputs: ["Purchases", "Labor", "Attention", "Data traces", "Political signals"],
    dependencies: ["Biological needs", "Social context", "Available options"],
    whoBenefits: ["Whoever can predict or shape behavior"],
    whoBearsCosts: ["Individuals when externalities are unpaid"],
    relatedSystems: ["attention", "data", "labor", "consumption", "trust"],
    uncertainties: [
      "How stable preferences are versus how much they are constructed by context",
      "How much of observed behavior is choice versus constraint",
    ],
    positiveEffects: ["Coordination, learning, production, care"],
    negativeExternalities: ["Herding, addiction-like loops, polarized attention"],
    unintendedConsequences: ["Systems that optimize a proxy of behavior can distort the behavior itself"],
    optimizesFor: "Local goals under limited attention — not a single global utility",
    resources: ["Time", "Attention", "Income", "Social standing"],
    gains: ["Goods, status, belonging, reduced friction"],
    risks: ["Manipulation, lock-in, misinformation, precarity"],
    whoPays: ["The person, and sometimes third parties via externalities"],
    encouragedBehavior: "Repeat what is rewarded and easy",
    unintendedBehavior: "Over-optimize for short-term cues at the expense of longer-term aims",
    claims: [
      {
        text: "People respond to prices, defaults, and social information — a robust finding, not a complete theory of mind.",
        evidence: "established",
      },
      {
        text: "Digital environments can reshape habits by changing feedback speed and social visibility.",
        evidence: "observed",
      },
    ],
    tensions: [
      { a: "Autonomy", b: "Designed choice architecture" },
      { a: "Short-term reward", b: "Long-term wellbeing" },
    ],
  }),
  N({
    id: "attention",
    name: "Attention",
    category: "psychological",
    layers: ["psychology", "information", "business"],
    tier: 0,
    importance: 10,
    evidenceLevel: "established",
    aliases: ["focus", "eyeballs"],
    description:
      "A scarce cognitive resource. Many information businesses treat it as inventory: time and focus that can be allocated, measured, and sold to advertisers or used to train ranking systems.",
    role: "Bottleneck through which information, products, and political messages must pass.",
    incentives: ["Orient to novelty, threat, social relevance, and unfinished tasks"],
    inputs: ["Stimuli", "Goals", "Arousal", "Social cues"],
    outputs: ["Engagement", "Memory traces", "What gets decided"],
    dependencies: ["Human nervous system", "Interface design"],
    whoBenefits: ["Attention merchants", "Anyone whose message is selected"],
    whoBearsCosts: ["People whose goals are interrupted", "Unranked speakers"],
    relatedSystems: ["engagement", "content", "advertising", "recommendation-algorithms"],
    uncertainties: ["How to measure 'quality' of attention versus duration"],
    positiveEffects: ["Learning, coordination, safety monitoring"],
    negativeExternalities: ["Distraction, anxiety, crowding-out of slower thought"],
    unintendedConsequences: ["Optimizing for time-on-task can reward outrage or novelty over accuracy"],
    optimizesFor: "Salience relative to current goals and threats",
    resources: ["Limited waking hours", "Working memory"],
    gains: ["Information, entertainment, social connection"],
    risks: ["Capture by high-arousal content"],
    whoPays: ["The attending person (time); sometimes advertisers (cash)"],
    encouragedBehavior: "Click, linger, return",
    unintendedBehavior: "Compulsive checking",
    tensions: [{ a: "User goals", b: "Platform engagement objectives" }],
  }),
  N({
    id: "data",
    name: "Data",
    category: "resource",
    layers: ["data", "ai", "business"],
    tier: 0,
    importance: 9,
    evidenceLevel: "established",
    aliases: ["records", "logs", "behavioral data"],
    description:
      "Recorded traces of the world and of people. In this model data is treated as an economic asset — costly to collect and store, valuable when it improves prediction — not merely a technical byproduct.",
    role: "Raw material for prediction, targeting, operations, and model training.",
    incentives: ["Collect more, keep longer, combine across sources"],
    inputs: ["Human behavior", "Sensors", "Transactions", "Public text"],
    outputs: ["Datasets", "Predictions", "Audit trails"],
    dependencies: ["Collection infrastructure", "Legal permission", "Storage"],
    whoBenefits: ["Holders who can act on it", "Buyers of targeting and risk scores"],
    whoBearsCosts: ["Subjects of collection (privacy, scoring)", "Firms that store it (liability)"],
    relatedSystems: ["data-collection", "privacy", "datasets", "machine-learning"],
    uncertainties: ["How much of the economic value of data is concentrated versus widely shared"],
    positiveEffects: ["Better logistics, medicine, fraud detection, search"],
    negativeExternalities: ["Surveillance, leakage, biased scoring"],
    unintendedConsequences: ["Once collected, reuse can exceed the original consent story"],
    optimizesFor: "Predictive value per record, subject to cost and law",
    resources: ["Behavior", "Instrumentation", "Compute"],
    gains: ["Prediction rents", "Product improvement"],
    risks: ["Breach, regulation, model poisoning, public backlash"],
    whoPays: ["Users (privacy), firms (capex), sometimes the public (externalities)"],
    encouragedBehavior: "Instrument everything that might later be useful",
    unintendedBehavior: "Hoarding low-quality data that still creates risk",
    claims: [
      {
        text: "Many digital products are financed by turning behavior into targeting or training inputs.",
        evidence: "observed",
      },
    ],
    tensions: [
      { a: "Personalization", b: "Privacy" },
      { a: "Data as asset", b: "Data as liability" },
    ],
  }),
  N({
    id: "technology",
    name: "Technology",
    category: "technology",
    layers: ["ai", "supply", "business"],
    tier: 0,
    evidenceLevel: "established",
    aliases: ["tech", "tools"],
    description:
      "Artifacts and methods that change what is cheap to do. Includes software, hardware, and techniques. Technology here is not autonomous — it is funded, regulated, and adopted inside other systems.",
    role: "Changes production functions: lowers some costs, creates new products, and shifts skill demand.",
    incentives: ["Adoption where it raises profit, status, or capability"],
    inputs: ["Research", "Capital", "Skills", "Components"],
    outputs: ["Products", "Productivity", "New failure modes"],
    dependencies: ["Energy", "Manufacturing", "Human operators and maintainers"],
    whoBenefits: ["Early adopters with complementary assets", "Inventors and owners of IP"],
    whoBearsCosts: ["Displaced task-holders", "Those exposed to new risks"],
    relatedSystems: ["innovation", "automation", "hardware", "software"],
    uncertainties: ["Pace and distribution of gains versus losses"],
    positiveEffects: ["Higher output per hour, new capabilities"],
    negativeExternalities: ["E-waste, energy use, skill obsolescence"],
    unintendedConsequences: ["Tools built for one goal get used for others"],
    optimizesFor: "Problem-solving under cost constraints — as defined by funders",
    resources: ["Capital", "Talent", "Infrastructure"],
    gains: ["Rents from better methods"],
    risks: ["Failed bets, regulation, commodity price collapse"],
    whoPays: ["Customers, workers in transition, taxpayers for public R&D"],
    encouragedBehavior: "Automate, scale, copy what works",
    unintendedBehavior: "Solutionism — applying a tool because it exists",
  }),
  N({
    id: "business-firms",
    name: "Companies",
    category: "company",
    layers: ["business", "money", "labor"],
    tier: 0,
    importance: 9,
    evidenceLevel: "established",
    aliases: ["firms", "corporations", "business", "company"],
    description:
      "Organizations that combine capital, labor, and technology to sell goods or services. This node is an archetype — not a specific firm. Legal form, governance, and market power vary widely.",
    role: "Convert inputs into products, capture revenue, and allocate surplus among workers, owners, and reinvestment.",
    incentives: ["Profit, growth, survival, and — for public firms — expected returns"],
    inputs: ["Capital", "Labor", "Materials", "Data", "Licenses"],
    outputs: ["Products", "Jobs", "Taxes", "Externalities"],
    dependencies: ["Customers", "Rule of law", "Infrastructure", "Suppliers"],
    whoBenefits: ["Owners when profitable", "Employees with good matches", "Customers when surplus is shared"],
    whoBearsCosts: ["Workers in bad matches", "Communities absorbing externalities"],
    relatedSystems: ["revenue", "profit", "employees", "investors", "competition"],
    uncertainties: ["How much observed 'purpose' talk changes capital allocation"],
    positiveEffects: ["Coordination of production at scale"],
    negativeExternalities: ["Pollution, market power, political spending"],
    unintendedConsequences: ["Metrics used internally can become the product"],
    optimizesFor: "A mix of profit, growth, and managerial goals — not a single function",
    resources: ["Capital", "Talent", "Distribution", "Reputation"],
    gains: ["Residual cash flow", "Strategic options"],
    risks: ["Competition, regulation, demand shocks, key-person and key-supplier risk"],
    whoPays: ["Customers (prices), workers (effort), sometimes the public"],
    encouragedBehavior: "Grow share, defend margins, reduce unit cost",
    unintendedBehavior: "Short-term earnings management; regulatory arbitrage",
    tensions: [
      { a: "Customer value", b: "Shareholder return" },
      { a: "Growth", b: "Resilience" },
    ],
  }),
  N({
    id: "capital",
    name: "Capital",
    category: "economic",
    layers: ["money", "business", "power"],
    tier: 0,
    importance: 9,
    evidenceLevel: "established",
    aliases: ["investment", "finance"],
    description:
      "Claims on future cash flows and the funds used to buy productive assets. Includes equity, credit, and retained earnings. Capital is not 'money in a vault' — it is a set of expectations and contracts.",
    role: "Allocate purchasing power toward projects, firms, and states that can promise a return or a public mandate.",
    incentives: ["Seek return adjusted for risk, liquidity, and control"],
    inputs: ["Savings", "Credit creation", "Profit"],
    outputs: ["Investment", "Ownership claims", "Discipline via cost of capital"],
    dependencies: ["Property rights", "Payment systems", "Credible accounting"],
    whoBenefits: ["Owners of scarce, productive, or legally protected claims"],
    whoBearsCosts: ["Borrowers in distress", "Those without access to cheap capital"],
    relatedSystems: ["investors", "credit", "markets", "interest-rates", "profit"],
    uncertainties: ["How much of return is productive contribution versus market power or luck"],
    positiveEffects: ["Funds long-horizon projects"],
    negativeExternalities: ["Boom-bust credit cycles", "Concentration of control"],
    unintendedConsequences: ["Fiduciary duty can crowd out unpriced goods"],
    optimizesFor: "Expected risk-adjusted return, as perceived by allocators",
    resources: ["Savings", "Collateral", "Legal enforceability"],
    gains: ["Interest, dividends, capital gains, control"],
    risks: ["Default, inflation, expropriation, illiquidity"],
    whoPays: ["Future cash-flow generators; sometimes taxpayers in crises"],
    encouragedBehavior: "Fund what screens well on return metrics",
    unintendedBehavior: "Underfund slow public goods; overfund fashionable trades",
    claims: [
      {
        text: "In market economies, investment is steered by expected return and the cost of capital.",
        evidence: "established",
      },
    ],
  }),
  N({
    id: "government",
    name: "Governments",
    category: "government",
    layers: ["power", "money"],
    tier: 0,
    importance: 9,
    evidenceLevel: "established",
    aliases: ["state", "public sector"],
    description:
      "Organizations with a claim to legitimate coercion in a territory: tax, regulate, spend, and provide or mandate public goods. This is an archetype covering democracies and other forms; incentives differ by regime.",
    role: "Set the rules of markets, provide security and some insurance, and respond to public and elite pressure.",
    incentives: ["Remain in power", "Fiscal capacity", "Perceived legitimacy", "Geopolitical position"],
    inputs: ["Taxes", "Information", "Votes or elite support", "Bureaucratic capacity"],
    outputs: ["Law", "Public spending", "Diplomacy", "Licenses"],
    dependencies: ["Compliance", "Administrative capacity", "Currency and debt markets"],
    whoBenefits: ["Coalitions that win office", "Recipients of spending and protection"],
    whoBearsCosts: ["Taxpayers", "Regulated parties", "Those outside the winning coalition"],
    relatedSystems: ["regulators", "courts", "taxes", "public-opinion", "lobbying"],
    uncertainties: ["How much policy is public-interest versus organized-interest"],
    positiveEffects: ["Public goods, rights enforcement, macroeconomic stabilization (contested in design)"],
    negativeExternalities: ["Corruption risk", "Poorly designed rules", "Conflict"],
    unintendedConsequences: ["Rules create niches for avoidance and lobbying"],
    optimizesFor: "A blend of public mandate and political survival — not a unified mind",
    resources: ["Legitimacy", "Force", "Fiscal base", "Information"],
    gains: ["Authority", "Revenue", "International standing"],
    risks: ["Electoral or elite overthrow", "Fiscal crisis", "Loss of legitimacy"],
    whoPays: ["Residents via tax, inflation, or reduced services"],
    encouragedBehavior: "Comply, petition, organize",
    unintendedBehavior: "Capture of agencies by the best-organized interests",
    tensions: [
      { a: "Legal influence", b: "Equal voice" },
      { a: "Growth", b: "Distribution" },
    ],
  }),
  N({
    id: "media",
    name: "Media",
    category: "information-system",
    layers: ["information", "power", "psychology"],
    tier: 0,
    evidenceLevel: "observed",
    aliases: ["press", "news media"],
    description:
      "Organizations and platforms that select, package, and distribute stories to a public. Includes legacy newsrooms and digital publishers. Business models (ads, subscriptions, patronage) shape what is cheap to produce.",
    role: "Filter and frame events for publics and elites; an input to opinion and to political incentives.",
    incentives: ["Audience", "Credibility (for some brands)", "Revenue", "Access to sources"],
    inputs: ["Events", "Leaks", "Journalism", "Audience metrics"],
    outputs: ["Stories", "Agendas", "Reputational rewards and punishments"],
    dependencies: ["Attention", "Legal speech rules", "Distribution platforms"],
    whoBenefits: ["Outlets with reach", "Actors who can stage newsworthy events"],
    whoBearsCosts: ["Subjects of coverage", "Audiences fed a skewed sample of the world"],
    relatedSystems: ["journalists", "news-ecosystem", "public-opinion", "attention", "advertising"],
    uncertainties: ["Net effect of digital distribution on accuracy versus speed"],
    positiveEffects: ["Accountability journalism", "Shared factual baselines (when they hold)"],
    negativeExternalities: ["Outrage cycles", "Under-covered slow risks"],
    unintendedConsequences: ["Metrics can pull coverage toward what spreads"],
    optimizesFor: "A mix of civic mission and audience capture — weights vary by outlet",
    resources: ["Talent", "Access", "Distribution", "Trust"],
    gains: ["Influence", "Revenue", "Status"],
    risks: ["Lawsuits", "Platform ranking changes", "Loss of trust"],
    whoPays: ["Audiences, advertisers, or patrons"],
    encouragedBehavior: "Publish what is timely and shareable",
    unintendedBehavior: "Horse-race and conflict frames crowding out mechanisms",
    tensions: [
      { a: "Accuracy", b: "Speed and reach" },
      { a: "Independence", b: "Access to power" },
    ],
  }),
  N({
    id: "ai-systems",
    name: "AI systems",
    category: "technology",
    layers: ["ai", "data", "business"],
    tier: 0,
    importance: 9,
    evidenceLevel: "observed",
    aliases: ["artificial intelligence", "AI", "models"],
    description:
      "Statistical and algorithmic systems that infer patterns and produce predictions, rankings, or generated content. In this model AI is embedded in firms, labs, clouds, and products — not a free-floating agent.",
    role: "Lower the cost of prediction, generation, and some kinds of decision support, which then feeds back into behavior and data.",
    incentives: ["Capability, product adoption, research prestige, and (for vendors) usage revenue"],
    inputs: ["Datasets", "Compute", "Energy", "Human feedback", "Research"],
    outputs: ["Predictions", "Generated media", "Automation", "New data"],
    dependencies: ["Chips", "Data centers", "Laboratories", "Electricity"],
    whoBenefits: ["Vendors and labs", "Users of cheaper inference", "Owners of complementary data and distribution"],
    whoBearsCosts: ["Workers in automated tasks", "People scored by models", "Energy systems"],
    relatedSystems: ["neural-networks", "llms", "gpus", "automation", "inference"],
    uncertainties: [
      "How far current methods scale",
      "Net labor demand after task automation",
    ],
    positiveEffects: ["Cheaper analysis, accessibility tools, scientific assistance"],
    negativeExternalities: ["Error at scale", "Copyright disputes", "Energy and water use"],
    unintendedConsequences: ["Synthetic content polluting future training data (hypothesis)"],
    optimizesFor: "Training and product objectives set by labs and buyers — not 'intelligence' in the abstract",
    resources: ["Data", "GPUs", "Researchers", "Capital"],
    gains: ["Product differentiation", "Cost reduction", "Strategic option value"],
    risks: ["Safety failures", "Regulation", "Commodity inference", "Reputational shocks"],
    whoPays: ["Customers of AI products; the public via externalities"],
    encouragedBehavior: "Delegate routine cognitive tasks to models",
    unintendedBehavior: "Over-trust fluent outputs; deskilling",
    claims: [
      {
        text: "Modern AI products sit on a stack of chips, energy, data, and distribution — not on algorithms alone.",
        evidence: "established",
      },
      {
        text: "Cheaper inference will reshape which tasks are automated; the net job effect is contested.",
        evidence: "contested",
      },
    ],
    tensions: [
      { a: "Capability", b: "Control and evaluation" },
      { a: "Open publication", b: "Safety and advantage" },
    ],
    geographicNote:
      "Design, capital, and cloud capacity are concentrated in a few countries; leading-edge fabrication is even more concentrated.",
  }),
  N({
    id: "labor",
    name: "Labor",
    category: "economic",
    layers: ["labor", "money", "business"],
    tier: 0,
    evidenceLevel: "established",
    aliases: ["work", "jobs"],
    description:
      "Human time and skill applied to production. Distinct from 'jobs' as legal positions. Automation can raise output per hour while reducing demand for particular tasks — both can be true.",
    role: "The human input to firms and public services; also a source of income that funds consumption.",
    incentives: ["Wages, meaning, status, security"],
    inputs: ["Skills", "Health", "Tools", "Management"],
    outputs: ["Goods and services", "On-the-job learning", "Workplace data"],
    dependencies: ["Demand for output", "Complementary capital"],
    whoBenefits: ["Workers with scarce complementary skills", "Employers of those workers"],
    whoBearsCosts: ["Workers in shrinking task bundles"],
    relatedSystems: ["employees", "wages", "skills", "automation", "productivity"],
    uncertainties: ["Elasticity of new task creation versus displacement"],
    positiveEffects: ["Livelihoods, skill formation, social structure"],
    negativeExternalities: ["Burnout, occupational injury, unpaid care work outside GDP"],
    unintendedConsequences: ["Productivity gains may accrue to owners unless bargaining or competition redistributes them"],
    optimizesFor: "A bargain among pay, effort, and outside options",
    resources: ["Time", "Skill", "Bargaining power"],
    gains: ["Income", "Identity", "Insurance via employment (where it exists)"],
    risks: ["Unemployment", "Skill obsolescence", "Unsafe conditions"],
    whoPays: ["Employers (wages); workers (effort); public (safety nets)"],
    encouragedBehavior: "Specialize where wages are high",
    unintendedBehavior: "Underinvestment in unpaid but valuable work",
    tensions: [
      { a: "Productivity", b: "Task-level employment" },
      { a: "Flexibility", b: "Security" },
    ],
  }),
  N({
    id: "consumption",
    name: "Consumption",
    category: "economic",
    layers: ["money", "business", "psychology"],
    tier: 0,
    evidenceLevel: "established",
    aliases: ["demand", "spending"],
    description:
      "Household and institutional purchasing. Closes the money loop: wages and transfers become revenue. Shaped by prices, credit, status, and convenience — not only by 'needs'.",
    role: "The demand side of markets; the cash that validates production.",
    incentives: ["Need, desire, status, habit, credit availability"],
    inputs: ["Income", "Credit", "Prices", "Marketing", "Identity"],
    outputs: ["Revenue for firms", "Waste", "Price signals"],
    dependencies: ["Distribution", "Payments", "Trust in sellers"],
    whoBenefits: ["Sellers of desired goods", "Consumers when surplus is large"],
    whoBearsCosts: ["Over-indebted households", "Environments absorbing waste"],
    relatedSystems: ["consumers", "revenue", "advertising", "credit", "identity"],
    uncertainties: ["How much of demand is 'manufactured' by marketing versus revealed preference"],
    positiveEffects: ["Material welfare", "Market feedback"],
    negativeExternalities: ["Resource use", "Status races"],
    unintendedConsequences: ["Credit-fueled consumption can mask wage stagnation for a time"],
    optimizesFor: "Perceived value under budget and attention constraints",
    resources: ["Income", "Credit", "Time to shop"],
    gains: ["Use value", "Signaling"],
    risks: ["Debt", "Addiction-like purchasing", "Regret"],
    whoPays: ["The buyer, sometimes future selves via debt"],
    encouragedBehavior: "Buy, upgrade, subscribe",
    unintendedBehavior: "Consume for identity rather than use",
  }),

  N({
    id: "engagement",
    name: "Engagement",
    category: "psychological",
    layers: ["psychology", "information", "data"],
    tier: 1,
    aliases: ["interaction", "time on site"],
    description:
      "Measurable interactions: clicks, dwell, shares, comments. A convenient proxy for attention — and a common training target for ranking systems.",
    role: "The operational stand-in for 'the user found this worth responding to'.",
    incentives: ["Platforms: maximize a chosen engagement metric; users: respond to salient content"],
    inputs: ["Content", "Rankings", "Notifications", "Social cues"],
    outputs: ["Data", "Ad inventory", "Habit"],
    dependencies: ["Attention", "Interface"],
    whoBenefits: ["Platforms selling ads or retention", "Creators who win the ranking"],
    whoBearsCosts: ["Users when the metric diverges from their goals"],
    relatedSystems: ["attention", "recommendation-algorithms", "advertising", "habit"],
    uncertainties: ["When engagement tracks satisfaction versus compulsion"],
    positiveEffects: ["Useful discovery", "Community"],
    negativeExternalities: ["Rage-bait, spam, sleep loss"],
    unintendedConsequences: ["Goodhart: the metric becomes the product"],
    optimizesFor: "Whatever the ranking objective encodes",
    resources: ["User time"],
    gains: ["Retention, data, revenue"],
    risks: ["Trust collapse", "Regulation of dark patterns"],
    whoPays: ["Users (time); advertisers (cash)"],
    encouragedBehavior: "Interact now",
    unintendedBehavior: "Performative conflict",
    tensions: [{ a: "Satisfaction", b: "Time-on-task" }],
    claims: [
      {
        text: "Engagement is a proxy, not identical to wellbeing or informedness.",
        evidence: "established",
      },
    ],
  }),
  N({
    id: "habit",
    name: "Habit",
    category: "psychological",
    layers: ["psychology"],
    tier: 1,
    description:
      "Cue–routine–reward loops that make behavior automatic. Product design often aims to become a habit because habits lower the cost of re-acquisition.",
    role: "Stabilizes repeated behavior, which stabilizes data and revenue.",
    incentives: ["Reduce cognitive effort; for firms, lock in recurrence"],
    inputs: ["Rewards", "Cues", "Ease"],
    outputs: ["Repeated behavior", "Switching costs of a psychological kind"],
    relatedSystems: ["reward", "convenience", "engagement", "retention"],
    uncertainties: ["How freely formed versus designed"],
    positiveEffects: ["Skill, reliability"],
    negativeExternalities: ["Compulsion"],
    unintendedConsequences: ["Hard-to-quit products even when users report regret"],
    optimizesFor: "Prediction error reduction in the brain; recurrence in the product",
    resources: ["Repetition", "Stable cues"],
    gains: ["Ease"],
    risks: ["Inflexibility"],
    whoPays: ["The person whose time is committed"],
    encouragedBehavior: "Open the app without deliberation",
    unintendedBehavior: "Checking as displacement of other goals",
    evidenceLevel: "observed",
  }),
  N({
    id: "trust",
    name: "Trust",
    category: "psychological",
    layers: ["psychology", "business", "power"],
    tier: 1,
    evidenceLevel: "observed",
    description:
      "Willingness to accept vulnerability based on expected behavior of people or institutions. Markets and media run on it; it is slow to build and can fail suddenly.",
    role: "Reduces transaction costs; its absence forces verification, law, or exit.",
    incentives: ["Appear reliable; sometimes, exploit residual trust"],
    inputs: ["Reputation", "Experience", "Institutions", "Social proof"],
    outputs: ["Exchange", "Compliance", "Attention to sources"],
    relatedSystems: ["media", "business-firms", "authority", "courts"],
    uncertainties: ["How much digital ratings substitute for thick trust"],
    positiveEffects: ["Trade, cooperation"],
    negativeExternalities: ["Trust in the untrustworthy"],
    unintendedConsequences: ["Brands harvest trust then spend it"],
    optimizesFor: "Expected reliability",
    whoBenefits: ["High-trust counterparties"],
    whoBearsCosts: ["The betrayed"],
    encouragedBehavior: "Transact without full inspection",
    unintendedBehavior: "Fraud at scale",
    tensions: [{ a: "Openness", b: "Verification" }],
  }),
  N({
    id: "social-status",
    name: "Social status",
    category: "psychological",
    layers: ["psychology", "business"],
    tier: 1,
    aliases: ["status", "prestige"],
    description:
      "Relative standing in a group. Drives consumption, career choice, and online performance. Not a universal law of every act — a recurring motive.",
    role: "A non-cash incentive that markets and platforms can attach metrics to (followers, titles, brands).",
    inputs: ["Audience", "Symbols", "Credentials"],
    outputs: ["Effort", "Consumption", "Coalition behavior"],
    relatedSystems: ["identity", "consumption", "social-proof"],
    uncertainties: ["How much status-seeking is culturally specific"],
    positiveEffects: ["Ambition, excellence"],
    negativeExternalities: ["Zero-sum races", "exclusion"],
    unintendedConsequences: ["Metrics of status crowd out unmeasured virtues"],
    optimizesFor: "Rank in a relevant audience",
    whoPays: ["Those who lose the race; audiences who subsidize display"],
    encouragedBehavior: "Signal success",
    unintendedBehavior: "Fraudulent signaling",
    evidenceLevel: "observed",
  }),
  N({
    id: "personalization",
    name: "Personalization",
    category: "technology",
    layers: ["data", "psychology", "ai"],
    tier: 1,
    description:
      "Adapting rankings, prices, or creative to a predicted individual. Relies on data and models; sold as relevance, criticized as manipulation or fragmentation.",
    role: "Closes the loop from behavior to future stimuli.",
    incentives: ["Raise conversion or engagement versus a generic baseline"],
    inputs: ["Profiles", "Context", "Inventory"],
    outputs: ["Ranked items", "Prices", "Messages"],
    relatedSystems: ["recommendation-algorithms", "privacy", "predictions"],
    uncertainties: ["Net civic effect of fragmented information diets"],
    positiveEffects: ["Less irrelevant noise", "Accessibility"],
    negativeExternalities: ["Filter effects", "Price discrimination"],
    unintendedConsequences: ["People cannot see the counterfactual feed"],
    optimizesFor: "A predicted individual objective (click, buy, watch)",
    tensions: [
      { a: "Relevance", b: "Shared reality" },
      { a: "Personalization", b: "Privacy" },
    ],
    evidenceLevel: "observed",
    claims: [
      {
        text: "Personalization can increase measured engagement; whether it increases filter bubbles is contested and context-dependent.",
        evidence: "contested",
      },
    ],
  }),
  N({
    id: "users",
    name: "Users",
    category: "human",
    layers: ["information", "data", "psychology"],
    tier: 1,
    aliases: ["end users"],
    description:
      "People in their role as operators of products and platforms. Overlaps with consumers and workers but emphasizes interaction and data generation.",
    role: "Supply attention and behavioral data; receive rankings, prices, and model outputs.",
    incentives: ["Get a job done with low friction; sometimes, seek entertainment or status"],
    inputs: ["Interfaces", "Recommendations", "Social context"],
    outputs: ["Clicks", "Content", "Payments", "Traces"],
    relatedSystems: ["social-platforms", "attention", "data-collection", "applications"],
    whoBenefits: ["Platforms with more users", "Users when the product fits"],
    whoBearsCosts: ["Users when the real product is the trace"],
    tensions: [
      { a: "User wellbeing", b: "Engagement optimization" },
      { a: "Free access", b: "Data extraction" },
    ],
    evidenceLevel: "established",
  }),
  N({
    id: "social-platforms",
    name: "Social platforms",
    category: "company",
    layers: ["information", "data", "business"],
    tier: 1,
    importance: 8,
    aliases: ["social media", "social networks"],
    description:
      "Multi-sided services that host user connections and content, typically ranked by algorithms and often financed by advertising. Named firms are examples of the type, not separately modeled here.",
    role: "Match people to people and to content; convert attention into inventory.",
    incentives: ["Retention, daily actives, ad yield, and regulatory survival"],
    inputs: ["Users", "Content", "Capital", "Cloud"],
    outputs: ["Feeds", "Ad slots", "Data", "Public discourse venues"],
    relatedSystems: ["recommendation-algorithms", "advertising", "users", "network-effects"],
    geographicNote: "A handful of large consumer platforms are headquartered in the US and China; usage is global.",
    tensions: [
      { a: "User wellbeing", b: "Engagement optimization" },
      { a: "Moderation", b: "Speech and growth" },
    ],
    evidenceLevel: "observed",
    claims: [
      {
        text: "Advertising-supported consumer platforms typically monetize attention and targeting, not the social graph alone.",
        evidence: "established",
      },
    ],
    optimizesFor: "A product objective such as engagement, retention, or revenue per user",
    resources: ["Network of users", "Data", "Ranking systems"],
    gains: ["Ad revenue", "Data advantages", "Distribution power"],
    risks: ["Attention recession", "Regulation", "Creator or user exodus"],
    whoPays: ["Advertisers in cash; users in attention and data"],
    whoBenefits: ["Shareholders", "Advertisers who convert", "Users who find value"],
    whoBearsCosts: ["Users harmed by ranking side-effects", "Publishers dependent on referral traffic"],
    encouragedBehavior: "Post, react, return",
    unintendedBehavior: "Performative conflict; professionalized influence",
  }),
  N({
    id: "recommendation-algorithms",
    name: "Recommendation algorithms",
    category: "technology",
    layers: ["ai", "information", "psychology"],
    tier: 1,
    importance: 8,
    aliases: ["ranking", "recommender", "feed ranking"],
    description:
      "Systems that score and order content, products, or people for a user. Objectives vary: engagement, retention, satisfaction, diversity, or revenue. The objective is a design choice, not a law of nature.",
    role: "Maximize a platform objective such as engagement, retention, satisfaction, or another optimization target.",
    inputs: ["User behavior", "Content", "Context", "Historical interactions"],
    outputs: ["Ranked content", "Recommendations", "Predictions"],
    incentives: ["Hit the chosen metric; remain cheap enough to serve"],
    dependencies: ["Data pipelines", "Compute", "Content inventory"],
    whoBenefits: ["Platforms", "Items that the model favors"],
    whoBearsCosts: ["Unranked speakers and products", "Users if the objective is misaligned"],
    relatedSystems: ["engagement", "personalization", "content", "machine-learning"],
    uncertainties: ["Long-run civic and mental-health effects of particular objectives"],
    positiveEffects: ["Increased relevance", "Discovery in huge catalogs"],
    negativeExternalities: ["Filter effects", "Popularity bias", "Incentives for spam"],
    unintendedConsequences: ["Behavioral feedback loops; creators chasing the ranking"],
    optimizesFor: "The specified platform objective — often a proxy",
    resources: ["Logs", "Features", "Serving infrastructure"],
    gains: ["Retention and yield"],
    risks: ["Metric gaming", "Scandal", "Regulatory transparency mandates"],
    whoPays: ["Users (attention allocation); sometimes advertisers"],
    encouragedBehavior: "Consume what scores well",
    unintendedBehavior: "Produce what scores well even if it is misleading",
    evidenceLevel: "observed",
    claims: [
      { text: "Recommenders increase measured engagement in many products.", evidence: "observed" },
      { text: "They can create filter bubbles; magnitude depends on product and audience.", evidence: "contested" },
      { text: "Feedback loops between ranking and behavior are a recognized mechanism.", evidence: "plausible" },
    ],
    tensions: [
      { a: "Relevance", b: "Diversity of exposure" },
      { a: "Short-term engagement", b: "Long-term trust" },
    ],
  }),
  N({
    id: "content",
    name: "Content",
    category: "information-system",
    layers: ["information", "psychology"],
    tier: 1,
    aliases: ["media content", "posts"],
    description:
      "Messages, video, text, and images competing for attention. Produced by professionals, users, and increasingly by models.",
    role: "The payload that ranking systems order and that attention selects.",
    inputs: ["Creators", "Events", "Models"],
    outputs: ["Attention", "Opinion", "Training text"],
    relatedSystems: ["media", "recommendation-algorithms", "llms"],
    evidenceLevel: "established",
  }),
  N({
    id: "journalists",
    name: "Journalists",
    category: "human",
    layers: ["information", "power"],
    tier: 1,
    description:
      "People whose job is to report and verify. Incentives include scoops, audience, professional norms, and employment in shrinking or shifting newsrooms.",
    role: "Produce accounts of events that feed media and public opinion.",
    inputs: ["Sources", "Documents", "Time"],
    outputs: ["Stories"],
    relatedSystems: ["news-ecosystem", "media", "public-opinion"],
    evidenceLevel: "observed",
    uncertainties: ["How much original reporting survives platform distribution"],
    whoBearsCosts: ["Reporters under threat or precarity"],
    whoBenefits: ["Publics that receive accurate accounts"],
  }),
  N({
    id: "news-ecosystem",
    name: "News ecosystem",
    category: "information-system",
    layers: ["information", "power"],
    tier: 1,
    description:
      "The overlapping set of newsrooms, wire services, aggregators, and influencers through which 'what happened' is constructed for a public.",
    role: "Aggregate and recirculate reports; set a rough agenda.",
    relatedSystems: ["journalists", "media", "social-platforms"],
    evidenceLevel: "observed",
    tensions: [{ a: "Verification", b: "Virality" }],
  }),
  N({
    id: "public-opinion",
    name: "Public opinion",
    category: "human",
    layers: ["information", "power", "psychology"],
    tier: 1,
    aliases: ["the public"],
    description:
      "Aggregate attitudes as measured by polls, votes, protests, and online traces. Noisy, constructed, and still politically consequential.",
    role: "Constrains and enables governments and brands.",
    inputs: ["Media", "Experience", "Identity", "Events"],
    outputs: ["Votes", "Boycotts", "Legitimacy"],
    relatedSystems: ["government", "media", "political-influence"],
    evidenceLevel: "observed",
    uncertainties: ["How well online samples represent publics"],
  }),
  N({
    id: "researchers",
    name: "Researchers",
    category: "human",
    layers: ["ai", "information", "labor"],
    tier: 1,
    aliases: ["scientists"],
    description:
      "People who produce public or proprietary knowledge. Includes university and industry labs. Career incentives (publication, grants, equity) shape topics.",
    role: "Generate methods and findings that later become products and policy inputs.",
    inputs: ["Prior work", "Funding", "Data", "Compute"],
    outputs: ["Publications", "Prototypes", "Talent"],
    relatedSystems: ["publications", "universities", "ai-laboratories"],
    evidenceLevel: "established",
  }),
  N({
    id: "data-collection",
    name: "Data collection",
    category: "infrastructure",
    layers: ["data", "business"],
    tier: 1,
    aliases: ["tracking", "instrumentation"],
    description:
      "The act of capturing behavior, sensors, and transactions. Spans first-party product logs, pixels, SDKs, and public scraping.",
    role: "Turn human activity into records.",
    inputs: ["Behavior", "Consent or legal basis", "SDKs"],
    outputs: ["Logs", "Broker feeds"],
    relatedSystems: ["privacy", "data-brokers", "users"],
    evidenceLevel: "established",
    tensions: [{ a: "Product improvement", b: "Minimization" }],
  }),
  N({
    id: "data-brokers",
    name: "Data brokers",
    category: "company",
    layers: ["data", "business"],
    tier: 1,
    description:
      "Firms that buy, infer, and sell attributes about people and companies. Often invisible to the subjects of the data.",
    role: "Make data liquid across organizational boundaries.",
    incentives: ["Coverage, freshness, exclusivity of attributes"],
    relatedSystems: ["data", "privacy", "advertising", "predictions"],
    evidenceLevel: "observed",
    whoBearsCosts: ["People who cannot see or contest the file"],
    uncertainties: ["Full graph of who sells what to whom is partly opaque"],
    geographicNote: "Large broker markets exist in the US; legal regimes differ sharply by jurisdiction.",
  }),
  N({
    id: "datasets",
    name: "Datasets",
    category: "resource",
    layers: ["data", "ai"],
    tier: 1,
    aliases: ["corpora", "training data"],
    description:
      "Assembled collections used for analytics or model training. Provenance, consent, and representativeness are often incomplete.",
    role: "The packaged form of data that machine learning actually consumes.",
    inputs: ["Collection", "Licensing", "Labeling"],
    outputs: ["Trained models", "Benchmarks"],
    relatedSystems: ["machine-learning", "llms", "privacy"],
    evidenceLevel: "established",
    uncertainties: ["Legal status of web-scale training corpora in multiple jurisdictions"],
  }),
  N({
    id: "machine-learning",
    name: "Machine learning",
    category: "technology",
    layers: ["ai", "data"],
    tier: 1,
    aliases: ["ML", "statistical learning"],
    description:
      "Methods that fit predictive functions to data. Broader than neural networks; includes the operational practice of training, evaluating, and deploying models.",
    role: "Convert datasets into predictors and generators.",
    relatedSystems: ["neural-networks", "predictions", "datasets"],
    evidenceLevel: "established",
  }),
  N({
    id: "predictions",
    name: "Predictions",
    category: "information-system",
    layers: ["data", "ai", "business"],
    tier: 1,
    aliases: ["scores", "forecasts"],
    description:
      "Outputs of models used to decide: credit, ranking, staffing, policing, inventory. A prediction is not a cause — acting on it can change the world it describes.",
    role: "Interface between data and decisions.",
    relatedSystems: ["machine-learning", "human-behavior", "credit"],
    evidenceLevel: "observed",
    tensions: [{ a: "Accuracy", b: "Fairness and contestability" }],
    unintendedConsequences: ["Performativity: people game the score"],
  }),
  N({
    id: "privacy",
    name: "Privacy",
    category: "institution",
    layers: ["data", "power", "psychology"],
    tier: 1,
    description:
      "Norms and rules about who may know what about whom. Simultaneously a right, a preference, and a compliance industry.",
    role: "Constraint on collection, retention, and cross-context use.",
    relatedSystems: ["data-collection", "regulators", "trust"],
    evidenceLevel: "observed",
    tensions: [{ a: "Privacy", b: "Personalization" }],
    geographicNote: "Legal baselines differ (e.g. EU GDPR versus more sectoral US rules) — a fact of law, not a ranking of virtue.",
  }),
  N({
    id: "neural-networks",
    name: "Neural networks",
    category: "technology",
    layers: ["ai"],
    tier: 1,
    aliases: ["deep learning"],
    description:
      "A class of models whose cost and capability have scaled with data and compute. The current backbone of most 'AI' products.",
    role: "Learnable function approximators sitting between datasets and inference.",
    relatedSystems: ["llms", "gpus", "training-infrastructure"],
    evidenceLevel: "established",
  }),
  N({
    id: "llms",
    name: "Large language models",
    category: "technology",
    layers: ["ai", "information"],
    tier: 1,
    aliases: ["LLM", "foundation models"],
    description:
      "Large neural models trained on text (and often more) that generate and transform language. Products wrap them with tools, retrieval, and policy.",
    role: "General-purpose linguistic interface and reasoning aid — with well-known failure modes (hallucination, bias).",
    relatedSystems: ["neural-networks", "datasets", "inference", "applications"],
    evidenceLevel: "observed",
    claims: [
      { text: "Quality has improved with scale of data, compute, and methods.", evidence: "observed" },
      { text: "They reliably 'understand' in the human sense.", evidence: "contested" },
    ],
  }),
  N({
    id: "gpus",
    name: "GPUs",
    category: "infrastructure",
    layers: ["ai", "supply"],
    tier: 1,
    importance: 8,
    aliases: ["accelerators", "AI chips"],
    description:
      "Specialized processors that made large-scale neural training economically thinkable. Supply is tight, capital-intensive, and geographically concentrated at the leading edge.",
    role: "The scarce physical bottleneck for training and, increasingly, inference.",
    relatedSystems: ["semiconductors", "training-infrastructure", "chip-foundries"],
    evidenceLevel: "established",
    geographicNote:
      "Leading-edge logic fabrication is concentrated in Taiwan, with critical equipment from the Netherlands and materials/tools from Japan, the US, and others.",
    whoBenefits: ["Designers of scarce accelerators", "Cloud resellers", "Customers who get access"],
    whoBearsCosts: ["Buyers facing allocation", "Anyone whose roadmap assumes unlimited compute"],
  }),
  N({
    id: "training-infrastructure",
    name: "Training infrastructure",
    category: "infrastructure",
    layers: ["ai", "supply"],
    tier: 1,
    aliases: ["clusters", "superpods"],
    description:
      "Networked accelerators, storage, and software used to train large models. A capital and energy project as much as a software one.",
    role: "Turn electricity, chips, and data into weights.",
    relatedSystems: ["gpus", "data-centers", "energy", "ai-laboratories"],
    evidenceLevel: "established",
  }),
  N({
    id: "ai-laboratories",
    name: "AI laboratories",
    category: "institution",
    layers: ["ai", "labor"],
    tier: 1,
    aliases: ["AI labs", "frontier labs"],
    description:
      "Organizations that train frontier models and publish or productize them. Mix of nonprofit, corporate, and hybrid forms. Competitive and collaborative at once.",
    role: "Concentrate talent, compute, and data to produce new model generations.",
    relatedSystems: ["researchers", "llms", "capital", "developers"],
    evidenceLevel: "observed",
    tensions: [{ a: "Publication", b: "Advantage and safety" }],
  }),
  N({
    id: "agents",
    name: "Software agents",
    category: "technology",
    layers: ["ai", "labor"],
    tier: 1,
    aliases: ["agents", "AI agents"],
    description:
      "Systems that call tools and take multi-step actions on a user's or firm's behalf. Early, uneven, and easy to over-claim.",
    role: "Move models from answering to doing.",
    relatedSystems: ["llms", "automation", "applications"],
    evidenceLevel: "plausible",
    uncertainties: ["Reliability in open-ended environments"],
  }),
  N({
    id: "automation",
    name: "Automation",
    category: "economic",
    layers: ["labor", "ai", "business"],
    tier: 1,
    importance: 7,
    description:
      "Substitution of machine processes for human tasks. Can raise productivity and shrink particular job categories at the same time. This model does not pick a single ideological conclusion.",
    role: "Change the mix of tasks inside production.",
    relatedSystems: ["productivity", "job-transformation", "ai-systems", "wages"],
    evidenceLevel: "observed",
    claims: [
      { text: "Automation raises output per hour in adopting firms, on average.", evidence: "observed" },
      { text: "It reduces demand for some tasks while creating others; net employment is contested.", evidence: "contested" },
    ],
    tensions: [{ a: "Productivity", b: "Demand for particular tasks" }],
    optimizesFor: "Lower unit cost or higher quality for the adopter",
    whoBenefits: ["Adopting owners and remaining complementary workers"],
    whoBearsCosts: ["Workers whose tasks are removed faster than they can switch"],
  }),
  N({
    id: "inference",
    name: "Inference",
    category: "technology",
    layers: ["ai"],
    tier: 1,
    aliases: ["model serving"],
    description:
      "Running a trained model to produce an output. Cost per token or query is a central economic variable for product design.",
    role: "The moment models meet users and other software.",
    relatedSystems: ["llms", "applications", "gpus", "cloud-infrastructure"],
    evidenceLevel: "established",
  }),
  N({
    id: "products",
    name: "Products",
    category: "economic",
    layers: ["business"],
    tier: 1,
    aliases: ["offers", "services"],
    description:
      "The packaged solution a firm sells. Sits between a problem and a distribution channel.",
    role: "Carry value to a customer and return revenue.",
    relatedSystems: ["distribution", "innovation", "consumers"],
    evidenceLevel: "established",
  }),
  N({
    id: "distribution",
    name: "Distribution",
    category: "economic",
    layers: ["business", "supply"],
    tier: 1,
    aliases: ["channels", "go to market"],
    description:
      "How an offer reaches a customer: stores, sales teams, app stores, search, feeds, partnerships. Often a harder problem than the product.",
    role: "The scarce path to demand.",
    relatedSystems: ["customer-acquisition", "social-platforms", "search-platforms"],
    evidenceLevel: "observed",
    whoBenefits: ["Owners of scarce channels"],
  }),
  N({
    id: "customer-acquisition",
    name: "Customer acquisition",
    category: "economic",
    layers: ["business"],
    tier: 1,
    aliases: ["CAC", "growth marketing"],
    description:
      "The process and cost of gaining a paying (or engaged) customer. Constrained by channel prices and conversion.",
    role: "Turn distribution into customers.",
    relatedSystems: ["advertising", "conversion", "cac"],
    evidenceLevel: "established",
  }),
  N({
    id: "revenue",
    name: "Revenue",
    category: "economic",
    layers: ["money", "business"],
    tier: 1,
    evidenceLevel: "established",
    description: "Cash in from customers. The beginning of the accounting identity that leads to profit or loss.",
    role: "Validate that someone paid.",
    relatedSystems: ["consumption", "profit", "business-firms"],
  }),
  N({
    id: "profit",
    name: "Profit",
    category: "economic",
    layers: ["money", "business"],
    tier: 1,
    evidenceLevel: "established",
    aliases: ["earnings", "surplus"],
    description:
      "Revenue minus costs (definitions vary). Residual that can be reinvested, distributed, or wasted.",
    role: "Signal and fuel for capital allocation inside the firm.",
    relatedSystems: ["revenue", "reinvestment", "shareholder-returns", "wages"],
    tensions: [{ a: "Wages and capex", b: "Distributions" }],
  }),
  N({
    id: "network-effects",
    name: "Network effects",
    category: "economic",
    layers: ["business"],
    tier: 1,
    description:
      "Value of a service rising with the number of compatible users. A common source of concentration — not automatic, and sometimes reversible.",
    role: "Can create winner-take-most dynamics and high switching costs.",
    relatedSystems: ["moats", "social-platforms", "competition"],
    evidenceLevel: "observed",
    claims: [
      { text: "Many communication and marketplace products exhibit network effects.", evidence: "established" },
      { text: "They always produce durable monopolies.", evidence: "contested" },
    ],
  }),
  N({
    id: "competition",
    name: "Competition",
    category: "market",
    layers: ["business"],
    tier: 1,
    description:
      "Rivalry for customers, talent, capital, or attention. Disciplines prices and spurs innovation — when it is real. Market power is the weakening of this node.",
    role: "A process, not a guarantee of consumer welfare.",
    relatedSystems: ["innovation", "pricing-power", "markets"],
    evidenceLevel: "established",
  }),
  N({
    id: "advertising",
    name: "Advertising",
    category: "economic",
    layers: ["business", "information", "money"],
    tier: 1,
    importance: 7,
    aliases: ["ads", "marketing"],
    description:
      "Paid influence over attention. Finances much of the consumer internet and a large share of media. Effectiveness is real and also routinely overstated.",
    role: "Convert attention into a budget that funds 'free' products and paid media.",
    relatedSystems: ["advertisers", "attention", "social-platforms", "customer-acquisition"],
    evidenceLevel: "observed",
    tensions: [
      { a: "Free access", b: "Targeting" },
      { a: "Brand safety", b: "Reach" },
    ],
    whoPays: ["Advertisers, ultimately via prices of advertised goods"],
    whoBenefits: ["Platforms and publishers", "Advertisers when incrementality is real"],
  }),
  N({
    id: "investors",
    name: "Investors",
    category: "human",
    layers: ["money", "power"],
    tier: 1,
    aliases: ["shareholders", "VCs", "asset managers"],
    description:
      "People and institutions that supply capital in exchange for claims. Includes retail, funds, and states. Time horizon and fiduciary rules vary.",
    role: "Price risk and allocate capital; exercise governance where ownership confers it.",
    relatedSystems: ["capital", "markets", "shareholder-returns", "business-firms"],
    evidenceLevel: "established",
    optimizesFor: "Return for a mandate (pension, endowment, speculator) — not 'the economy'",
    whoPays: ["Entrepreneurs and workers via the cost of capital; LPs via fees"],
  }),
  N({
    id: "banks",
    name: "Banks",
    category: "institution",
    layers: ["money", "power"],
    tier: 1,
    aliases: ["lenders"],
    description:
      "Institutions that take deposits or wholesale funding and extend credit. They create purchasing power when they lend, within regulatory and capital constraints.",
    role: "Operate the credit channel and payment rails.",
    relatedSystems: ["credit", "debt", "government", "interest-rates"],
    evidenceLevel: "established",
    claims: [
      {
        text: "Bank lending is a primary way new deposit balances appear in modern monetary systems.",
        evidence: "established",
      },
    ],
  }),
  N({
    id: "credit",
    name: "Credit",
    category: "economic",
    layers: ["money"],
    tier: 1,
    aliases: ["loans"],
    description:
      "Purchasing power now against a promise to pay later. Enables investment and consumption smoothing; also leverage and crises.",
    role: "Time-shift spending.",
    relatedSystems: ["banks", "debt", "interest-rates", "consumption"],
    evidenceLevel: "established",
  }),
  N({
    id: "markets",
    name: "Markets",
    category: "market",
    layers: ["money", "business"],
    tier: 1,
    aliases: ["financial markets", "exchanges"],
    description:
      "Venues where claims and goods are priced. 'The market' is not a person; it is an aggregation of orders under rules.",
    role: "Discover prices and reallocate risk — imperfectly.",
    relatedSystems: ["investors", "capital", "media"],
    evidenceLevel: "established",
  }),
  N({
    id: "debt",
    name: "Debt",
    category: "economic",
    layers: ["money", "power"],
    tier: 1,
    description:
      "Outstanding credit. A claim that does not share upside the way equity does. High aggregate debt raises fragility to rate and income shocks.",
    role: "Stock counterpart to the credit flow.",
    relatedSystems: ["credit", "banks", "interest-rates"],
    evidenceLevel: "established",
  }),
  N({
    id: "regulators",
    name: "Regulators",
    category: "government",
    layers: ["power"],
    tier: 1,
    description:
      "Agencies that write and enforce rules under statute. Not identical to 'the government' and not automatically captured or public-spirited.",
    role: "Translate law into licenses, standards, and penalties.",
    relatedSystems: ["government", "lobbying", "courts", "business-firms"],
    evidenceLevel: "established",
    tensions: [{ a: "Expertise", b: "Democratic control" }],
  }),
  N({
    id: "lobbying",
    name: "Lobbying",
    category: "institution",
    layers: ["power", "business"],
    tier: 1,
    description:
      "Legal organized persuasion of officials. Includes advocacy by firms, unions, and NGOs. Distinct from bribery; still a channel of unequal voice.",
    role: "Transmit organized preferences into the rule-making process.",
    relatedSystems: ["government", "regulators", "political-influence", "business-firms"],
    evidenceLevel: "observed",
    claims: [
      { text: "Lobbying is a lawful and documented practice in many democracies.", evidence: "established" },
      { text: "It systematically determines policy against median voters.", evidence: "contested" },
    ],
  }),
  N({
    id: "courts",
    name: "Courts",
    category: "institution",
    layers: ["power"],
    tier: 1,
    description:
      "Adjudicative bodies that interpret law, resolve disputes, and constrain other institutions — to the degree independence and capacity hold.",
    role: "Settle conflicts and review agency action.",
    relatedSystems: ["government", "regulators", "business-firms"],
    evidenceLevel: "established",
  }),
  N({
    id: "political-influence",
    name: "Political influence",
    category: "economic",
    layers: ["power"],
    tier: 1,
    description:
      "Ability to shape collective decisions without necessarily holding office: money, media, networks, expertise, street presence. Not a synonym for conspiracy.",
    role: "A family of mechanisms between private actors and public authority.",
    relatedSystems: ["lobbying", "media", "public-opinion", "capital"],
    evidenceLevel: "observed",
  }),
  N({
    id: "public-pressure",
    name: "Public pressure",
    category: "human",
    layers: ["power", "information"],
    tier: 1,
    aliases: ["protest", "backlash"],
    description:
      "Organized or viral public demand that officials or firms change course. A counterweight to quiet lobbying — when it can sustain attention.",
    role: "Raise the political cost of inaction or of a policy.",
    relatedSystems: ["public-opinion", "media", "government"],
    evidenceLevel: "observed",
  }),
  N({
    id: "semiconductors",
    name: "Semiconductors",
    category: "resource",
    layers: ["supply", "ai"],
    tier: 1,
    importance: 8,
    aliases: ["chips"],
    description:
      "The physical substrate of computing. Design, equipment, materials, and fabrication are specialized and globally split.",
    role: "Bind software ambition to a slow, expensive, geographic supply chain.",
    relatedSystems: ["gpus", "chip-foundries", "hardware", "manufacturing"],
    evidenceLevel: "established",
    geographicNote:
      "Leading-edge manufacturing is concentrated in East Asia; lithography equipment is concentrated in Europe; design is concentrated in the US and elsewhere.",
  }),
  N({
    id: "hardware",
    name: "Hardware",
    category: "infrastructure",
    layers: ["supply", "ai"],
    tier: 1,
    aliases: ["devices", "servers"],
    description: "Physical machines: phones, PCs, servers, networking. The body software inhabits.",
    role: "Deliver compute and interfaces to people and data centers.",
    relatedSystems: ["semiconductors", "manufacturing", "data-centers"],
    evidenceLevel: "established",
  }),
  N({
    id: "data-centers",
    name: "Data centers",
    category: "infrastructure",
    layers: ["supply", "ai", "data"],
    tier: 1,
    description:
      "Buildings that pack compute, storage, and networking with power and cooling. The physical form of 'the cloud'.",
    role: "Host other people's software and models.",
    relatedSystems: ["cloud-infrastructure", "energy", "hardware"],
    evidenceLevel: "established",
    geographicNote: "Sited where power, land, fiber, and permits align — often clustered.",
  }),
  N({
    id: "cloud-infrastructure",
    name: "Cloud infrastructure",
    category: "infrastructure",
    layers: ["supply", "ai", "business"],
    tier: 1,
    aliases: ["cloud", "hyperscalers"],
    description:
      "On-demand compute, storage, and networking sold as a service. A few large providers dominate many markets. This node is the type, not a named vendor.",
    role: "Rent the factory in which software and training run.",
    relatedSystems: ["data-centers", "training-infrastructure", "software"],
    evidenceLevel: "observed",
    whoBenefits: ["Providers with scale", "Startups that avoid capex"],
    tensions: [{ a: "Convenience", b: "Concentration and lock-in" }],
  }),
  N({
    id: "energy",
    name: "Energy",
    category: "resource",
    layers: ["supply", "ai"],
    tier: 1,
    aliases: ["electricity", "power"],
    description:
      "Work in physical form. Binding constraint for data centers, manufacturing, and households. Mix and carbon intensity vary by place.",
    role: "Ultimate input to computation and industry.",
    relatedSystems: ["data-centers", "manufacturing"],
    evidenceLevel: "established",
  }),
  N({
    id: "manufacturing",
    name: "Manufacturing",
    category: "infrastructure",
    layers: ["supply", "labor"],
    tier: 1,
    description: "Transformation of materials into components and goods. Still the base of hardware and many consumer products.",
    role: "Make the physical world of the graph.",
    relatedSystems: ["raw-materials", "semiconductors", "labor"],
    evidenceLevel: "established",
  }),
  N({
    id: "employees",
    name: "Employees",
    category: "human",
    layers: ["labor", "business"],
    tier: 1,
    aliases: ["staff"],
    description:
      "People in a wage or salary relationship with a firm. Receive pay; produce output; generate workplace data.",
    role: "The contractual form of much labor.",
    relatedSystems: ["labor", "wages", "productivity", "business-firms"],
    evidenceLevel: "established",
  }),
  N({
    id: "skills",
    name: "Skills",
    category: "resource",
    layers: ["labor"],
    tier: 1,
    aliases: ["human capital"],
    description:
      "Learned capabilities that make labor productive in particular tasks. Depreciate when tools change.",
    role: "Complement or substitute relative to automation.",
    relatedSystems: ["universities", "job-transformation", "wages"],
    evidenceLevel: "observed",
  }),
  N({
    id: "job-transformation",
    name: "Job transformation",
    category: "economic",
    layers: ["labor", "ai"],
    tier: 1,
    aliases: ["task change", "displacement"],
    description:
      "The rewriting of task bundles inside occupations. Distinct from 'jobs disappearing' as a headline. Some tasks vanish, some appear, many mix.",
    role: "The labor-market expression of automation and demand shifts.",
    relatedSystems: ["automation", "skills", "workers"],
    evidenceLevel: "observed",
    claims: [
      { text: "Task content of occupations changes continuously.", evidence: "established" },
      { text: "AI will eliminate most jobs in a short period.", evidence: "speculative" },
    ],
  }),
  N({
    id: "productivity",
    name: "Productivity",
    category: "economic",
    layers: ["labor", "business"],
    tier: 1,
    description:
      "Output per input, usually per hour. Raised by tools, organization, and skill. Distribution of the gains is a separate question.",
    role: "The real resource that wages, profits, and prices ultimately draw on.",
    relatedSystems: ["automation", "profit", "wages"],
    evidenceLevel: "established",
    tensions: [{ a: "Measured output", b: "Unmeasured quality and care" }],
  }),
  N({
    id: "consumers",
    name: "Consumers",
    category: "human",
    layers: ["money", "business", "psychology"],
    tier: 1,
    aliases: ["customers", "buyers"],
    description:
      "People in their role as purchasers. Overlap with users and workers, but the cash register is the point.",
    role: "Close the revenue loop.",
    relatedSystems: ["consumption", "products", "advertising"],
    evidenceLevel: "established",
  }),

  N({
    id: "curiosity",
    name: "Curiosity",
    category: "psychological",
    layers: ["psychology"],
    tier: 2,
    description: "Drive to close information gaps. Feeds exploration and also clickbait that fakes a gap.",
    role: "A mechanism that attention systems can hook.",
    relatedSystems: ["attention", "novelty"],
    evidenceLevel: "observed",
  }),
  N({
    id: "reward",
    name: "Reward",
    category: "psychological",
    layers: ["psychology"],
    tier: 2,
    description: "Experienced payoff that reinforces behavior. Variable schedules are widely used in product design.",
    role: "Glue of habit loops.",
    relatedSystems: ["habit", "engagement"],
    evidenceLevel: "observed",
  }),
  N({
    id: "fear",
    name: "Fear",
    category: "psychological",
    layers: ["psychology", "information"],
    tier: 2,
    description: "Threat response that commandeers attention. Useful for survival; expensive as a media diet.",
    role: "High-salience input to attention.",
    relatedSystems: ["attention", "media"],
    evidenceLevel: "observed",
  }),
  N({
    id: "identity",
    name: "Identity",
    category: "psychological",
    layers: ["psychology"],
    tier: 2,
    description: "Stories of who we are, including group membership. Shapes consumption, media, and politics.",
    role: "A filter on what counts as 'for people like me'.",
    relatedSystems: ["tribal-behavior", "consumption", "public-opinion"],
    evidenceLevel: "observed",
  }),

  N({
    id: "tribal-behavior",
    name: "Tribal behavior",
    category: "psychological",
    layers: ["psychology", "power"],
    tier: 2,
    aliases: ["in-group", "coalition"],
    description:
      "Coalition and in-group/out-group dynamics. A recurring pattern in politics and online crowds — not a claim that humans are only tribal.",
    role: "Shapes which information is trusted and which groups can mobilize.",
    relatedSystems: ["identity", "public-opinion", "social-proof"],
    evidenceLevel: "observed",
    uncertainties: ["How much of online polarization is tribal versus incentive-driven content supply"],
  }),
  N({
    id: "social-proof",
    name: "Social proof",
    category: "psychological",
    layers: ["psychology"],
    tier: 2,
    description: "Using others' behavior as evidence. Rankings, reviews, and like-counts industrialize it.",
    role: "Cheap heuristic; also a manipulation surface.",
    relatedSystems: ["engagement", "trust"],
    evidenceLevel: "observed",
  }),
  N({
    id: "novelty",
    name: "Novelty",
    category: "psychological",
    layers: ["psychology"],
    tier: 2,
    description: "Newness as a salience cue. Feeds both learning and infinite-scroll design.",
    role: "Competes with habit for attention.",
    relatedSystems: ["attention", "curiosity"],
    evidenceLevel: "observed",
  }),
  N({
    id: "loss-aversion",
    name: "Loss aversion",
    category: "psychological",
    layers: ["psychology", "business"],
    tier: 2,
    description:
      "Losses often loom larger than equal gains in experimental settings. Used in pricing and retention; not a universal law of every decision.",
    role: "A pricing and UX lever.",
    relatedSystems: ["consumption", "retention"],
    evidenceLevel: "observed",
    uncertainties: ["Effect sizes vary by context; replication debates exist in parts of the literature"],
  }),
  N({
    id: "scarcity",
    name: "Scarcity",
    category: "psychological",
    layers: ["psychology", "business"],
    tier: 2,
    description: "Perceived shortage that raises urgency. Sometimes real, sometimes staged.",
    role: "Accelerant for attention and purchase.",
    relatedSystems: ["attention", "consumption"],
    evidenceLevel: "observed",
  }),
  N({
    id: "publications",
    name: "Publications",
    category: "information-system",
    layers: ["information", "ai"],
    tier: 2,
    aliases: ["papers", "journals"],
    description: "The formal record of research. Slow, status-bearing, and increasingly paralleled by preprints and blogs.",
    role: "Move ideas from labs toward industry and policy.",
    relatedSystems: ["researchers", "universities", "ai-laboratories"],
    evidenceLevel: "established",
  }),
  N({
    id: "data-storage",
    name: "Data storage",
    category: "infrastructure",
    layers: ["data"],
    tier: 2,
    description: "Retention of records. Creates option value and breach surface.",
    role: "Hold collection until analysis.",
    relatedSystems: ["data-collection", "cloud-infrastructure", "privacy"],
    evidenceLevel: "established",
  }),
  N({
    id: "applications",
    name: "Applications",
    category: "technology",
    layers: ["ai", "business"],
    tier: 2,
    aliases: ["apps", "products wrapping models"],
    description: "Software products that wrap models, data, and UX. Where most people meet AI.",
    role: "Deliver inference into a workflow.",
    relatedSystems: ["inference", "developers", "users"],
    evidenceLevel: "observed",
  }),
  N({
    id: "advertisers",
    name: "Advertisers",
    category: "company",
    layers: ["business", "money"],
    tier: 2,
    description: "Organizations that buy attention. Their budgets are the cash engine of ad-supported media and platforms.",
    role: "Pay for inventory.",
    relatedSystems: ["advertising", "social-platforms", "revenue"],
    evidenceLevel: "established",
  }),
  N({
    id: "developers",
    name: "Developers",
    category: "human",
    layers: ["labor", "ai"],
    tier: 2,
    aliases: ["software engineers"],
    description: "People who build and maintain software and model integrations.",
    role: "Translate models and requirements into running systems.",
    relatedSystems: ["software", "applications", "ai-laboratories"],
    evidenceLevel: "established",
  }),
  N({
    id: "software",
    name: "Software",
    category: "technology",
    layers: ["supply", "business", "ai"],
    tier: 2,
    description: "Instructions that run on hardware. High fixed cost, low marginal copy cost — a core economic peculiarity of the digital world.",
    role: "Encode processes; sit on top of chips and clouds.",
    relatedSystems: ["hardware", "cloud-infrastructure", "developers"],
    evidenceLevel: "established",
  }),
  N({
    id: "shareholder-returns",
    name: "Shareholder returns",
    category: "economic",
    layers: ["money"],
    tier: 2,
    aliases: ["dividends", "buybacks"],
    description: "Cash or price appreciation delivered to owners. One use of profit, not the only one.",
    role: "Close the investor loop.",
    relatedSystems: ["profit", "investors", "capital"],
    evidenceLevel: "established",
  }),
  N({
    id: "taxes",
    name: "Taxes",
    category: "economic",
    layers: ["money", "power"],
    tier: 2,
    description: "Compulsory transfers to government. Fund public goods and reshape after-tax incentives.",
    role: "Link private cash flows to public capacity.",
    relatedSystems: ["government", "revenue", "consumers"],
    evidenceLevel: "established",
  }),
  N({
    id: "interest-rates",
    name: "Interest rates",
    category: "economic",
    layers: ["money", "power"],
    tier: 2,
    aliases: ["cost of capital", "policy rate"],
    description:
      "The price of time and risk in credit markets, strongly influenced by central banks in many economies. A high-leverage node for housing, investment, and valuations.",
    role: "Discount the future.",
    relatedSystems: ["credit", "capital", "banks"],
    evidenceLevel: "established",
  }),
  N({
    id: "universities",
    name: "Universities",
    category: "institution",
    layers: ["labor", "information", "ai"],
    tier: 2,
    aliases: ["higher education"],
    description: "Institutions that credential, teach, and host much basic research. Funded by a mix of states, students, donors, and industry.",
    role: "Produce skills and publications; a talent pipeline for labs and firms.",
    relatedSystems: ["researchers", "skills", "publications"],
    evidenceLevel: "established",
  }),
  N({
    id: "natural-resources",
    name: "Natural resources",
    category: "resource",
    layers: ["supply"],
    tier: 2,
    aliases: ["minerals", "fuels"],
    description: "Extracted inputs: energy minerals, metals, water, land. Geography is not optional.",
    role: "Start of many supply chains.",
    relatedSystems: ["raw-materials", "energy"],
    evidenceLevel: "established",
    geographicNote: "Deposits and water are unevenly distributed; processing is often elsewhere.",
  }),
  N({
    id: "chip-foundries",
    name: "Chip foundries",
    category: "company",
    layers: ["supply", "ai"],
    tier: 2,
    aliases: ["fabs", "foundries"],
    description:
      "Plants that fabricate chips for designers. Leading-edge capacity is scarce and slow to copy. Archetype, not a named company node.",
    role: "Turn designs and materials into working silicon.",
    relatedSystems: ["semiconductors", "gpus", "manufacturing"],
    evidenceLevel: "established",
    geographicNote: "A very small number of firms operate at the leading process nodes, with sites concentrated in East Asia.",
  }),
  N({
    id: "supply-chains",
    name: "Supply chains",
    category: "infrastructure",
    layers: ["supply"],
    tier: 2,
    description: "The networked logistics of making and moving goods. Efficiency often traded against redundancy.",
    role: "Connect resources to consumers through many hands.",
    relatedSystems: ["manufacturing", "distribution"],
    evidenceLevel: "established",
    tensions: [{ a: "Just-in-time cost", b: "Resilience" }],
  }),
  N({
    id: "switching-costs",
    name: "Switching costs",
    category: "economic",
    layers: ["business"],
    tier: 2,
    description: "Friction of leaving a product: data, habits, contracts, retraining. A quiet form of power.",
    role: "Support retention and pricing power.",
    relatedSystems: ["moats", "habit", "cloud-infrastructure"],
    evidenceLevel: "observed",
  }),
  N({
    id: "moats",
    name: "Moats",
    category: "economic",
    layers: ["business"],
    tier: 2,
    aliases: ["barriers to entry"],
    description:
      "Durable advantages: network effects, scale, switching costs, IP, regulation. A metaphor from investors, not a physical wall.",
    role: "Protect returns from competition — when they actually exist.",
    relatedSystems: ["network-effects", "switching-costs", "pricing-power"],
    evidenceLevel: "plausible",
    uncertainties: ["Many claimed moats are temporary"],
  }),
  N({
    id: "pricing-power",
    name: "Pricing power",
    category: "economic",
    layers: ["business", "money"],
    tier: 2,
    description: "Ability to raise price without losing the business. A symptom of scarce alternatives or strong brands.",
    role: "Translate advantage into margin.",
    relatedSystems: ["moats", "competition", "margins"],
    evidenceLevel: "observed",
  }),
  N({
    id: "economies-of-scale",
    name: "Economies of scale",
    category: "economic",
    layers: ["business", "supply"],
    tier: 2,
    description: "Unit cost falling as volume rises. Software and fabs both show versions of this, for different reasons.",
    role: "Reward size; can entrench leaders.",
    relatedSystems: ["cloud-infrastructure", "manufacturing", "margins"],
    evidenceLevel: "established",
  }),
  N({
    id: "innovation",
    name: "Innovation",
    category: "economic",
    layers: ["business", "ai"],
    tier: 2,
    description: "New combinations that customers or processes adopt. Not the same as patents or press releases.",
    role: "Reset products and cost curves; raise the competitive bar.",
    relatedSystems: ["competition", "products", "researchers"],
    evidenceLevel: "observed",
  }),
  N({
    id: "inequality",
    name: "Inequality",
    category: "economic",
    layers: ["labor", "money", "power"],
    tier: 2,
    description:
      "Uneven distribution of income, wealth, or capability. Causes and remedies are contested; the fact of dispersion is not.",
    role: "An outcome of markets, policy, and inheritance that then feeds back into power and demand.",
    relatedSystems: ["wages", "capital", "political-influence"],
    evidenceLevel: "observed",
    claims: [
      { text: "Income and wealth are unevenly distributed in measured economies.", evidence: "established" },
      { text: "A single cause (technology, trade, policy) dominates.", evidence: "contested" },
    ],
  }),
  N({
    id: "reinvestment",
    name: "Reinvestment",
    category: "economic",
    layers: ["money", "business"],
    tier: 2,
    description: "Plowing surplus back into capacity, R&D, or acquisitions rather than distributing it.",
    role: "The firm's internal capital market.",
    relatedSystems: ["profit", "growth", "innovation"],
    evidenceLevel: "established",
  }),
  N({
    id: "growth",
    name: "Growth",
    category: "economic",
    layers: ["business", "money"],
    tier: 2,
    description: "Expansion of output, users, or revenue. A goal for many firms and states; not identical to welfare.",
    role: "Scale that can improve unit economics or merely inflate.",
    relatedSystems: ["reinvestment", "revenue", "labor"],
    evidenceLevel: "observed",
  }),
  N({
    id: "workers",
    name: "Workers",
    category: "human",
    layers: ["labor"],
    tier: 2,
    description: "People who sell labor, including contractors and informal work — broader than 'employees'.",
    role: "The human supply of labor.",
    relatedSystems: ["labor", "employees", "job-transformation"],
    evidenceLevel: "established",
  }),
  N({
    id: "wages",
    name: "Wages",
    category: "economic",
    layers: ["labor", "money"],
    tier: 2,
    aliases: ["pay", "compensation"],
    description: "The price of labor. Set by bargaining, productivity, law, and outside options.",
    role: "Link production to household consumption.",
    relatedSystems: ["employees", "consumption", "inequality"],
    evidenceLevel: "established",
  }),
  N({
    id: "convenience",
    name: "Convenience",
    category: "psychological",
    layers: ["psychology", "business"],
    tier: 2,
    description: "Low friction. A dominant consumer preference and a competitive weapon.",
    role: "Makes habit and lock-in easier.",
    relatedSystems: ["habit", "distribution"],
    evidenceLevel: "observed",
  }),
  N({
    id: "authority",
    name: "Authority",
    category: "psychological",
    layers: ["psychology", "power"],
    tier: 2,
    description: "Deference to credentialed or official sources. Can transmit expertise or launder error.",
    role: "A shortcut for trust.",
    relatedSystems: ["trust", "government", "media"],
    evidenceLevel: "observed",
  }),
  N({
    id: "conversion",
    name: "Conversion",
    category: "economic",
    layers: ["business"],
    tier: 2,
    description: "Turning a visitor or lead into a desired action, often a purchase.",
    role: "The hinge of the funnel.",
    relatedSystems: ["customer-acquisition", "revenue"],
    evidenceLevel: "established",
  }),
  N({
    id: "retention",
    name: "Retention",
    category: "economic",
    layers: ["business", "psychology"],
    tier: 2,
    description: "Keeping a customer or user. Usually cheaper than acquiring another — hence habit and switching-cost design.",
    role: "Stabilize revenue.",
    relatedSystems: ["habit", "ltv", "switching-costs"],
    evidenceLevel: "observed",
  }),
  N({
    id: "cac",
    name: "CAC",
    category: "economic",
    layers: ["business"],
    tier: 2,
    aliases: ["customer acquisition cost"],
    description: "Fully loaded cost to acquire a customer. A constraint on paid growth.",
    role: "Price of the funnel.",
    relatedSystems: ["customer-acquisition", "ltv", "advertising"],
    evidenceLevel: "established",
  }),
  N({
    id: "ltv",
    name: "LTV",
    category: "economic",
    layers: ["business"],
    tier: 2,
    aliases: ["lifetime value"],
    description: "Expected discounted gross profit from a customer. Often estimated badly; still a governing ratio with CAC.",
    role: "Ceiling on what acquisition may cost.",
    relatedSystems: ["retention", "cac", "profit"],
    evidenceLevel: "observed",
  }),
  N({
    id: "margins",
    name: "Margins",
    category: "economic",
    layers: ["business", "money"],
    tier: 2,
    description: "Profit as a share of revenue. Encode pricing power and cost structure.",
    role: "A compact health metric of the offer.",
    relatedSystems: ["profit", "pricing-power", "economies-of-scale"],
    evidenceLevel: "established",
  }),
  N({
    id: "search-platforms",
    name: "Search platforms",
    category: "company",
    layers: ["information", "business"],
    tier: 2,
    aliases: ["search engines"],
    description:
      "Services that rank the web or an app corpus in response to a query. A major distribution chokepoint. Archetype, not a named firm.",
    role: "Allocate discovery; sell intent-rich ads.",
    relatedSystems: ["advertising", "distribution", "recommendation-algorithms"],
    evidenceLevel: "observed",
  }),
  N({
    id: "information-power",
    name: "Information power",
    category: "economic",
    layers: ["power", "information"],
    tier: 2,
    description:
      "Ability to shape what others know, see, or believe. Distinct from formal authority and from capital, though often correlated.",
    role: "A mechanism of influence via agenda and framing.",
    relatedSystems: ["media", "social-platforms", "political-influence"],
    evidenceLevel: "plausible",
  }),
  N({
    id: "market-power",
    name: "Market power",
    category: "economic",
    layers: ["business", "power"],
    tier: 2,
    description: "Ability to set terms without losing the market. The economic name for weak competition.",
    role: "Translate structure into price and politics.",
    relatedSystems: ["competition", "pricing-power", "regulators"],
    evidenceLevel: "observed",
  }),
  N({
    id: "raw-materials",
    name: "Raw materials",
    category: "resource",
    layers: ["supply"],
    tier: 2,
    description: "Processed resources ready for manufacturing: chemicals, metals, substrates, gases.",
    role: "Mid-chain between extraction and fabrication.",
    relatedSystems: ["natural-resources", "manufacturing"],
    evidenceLevel: "established",
  }),
];
